// Videos strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "nav.videos": "مرئيات",
    "vid.title": "مرئيات",
    "vid.lead": "مقاطع مرئية من موقع دار الإسلام (IslamHouse)، أحد مصادر الحزمة العلمية المعتمدة. تُعرض من موقعهم مباشرة كما نُشرت.",
    "vid.all": "الكل", "vid.part": "الجزء {n}",
    // Counted text (tn): Arabic has a form for 0, 1, 2, 3–10, 11–99; the plain key is the form for 100 and more.
    "vid.count": "{n} مقطع", "vid.count.zero": "لا مقاطع", "vid.count.one": "مقطع واحد", "vid.count.two": "مقطعان",
    "vid.count.few": "{n} مقاطع", "vid.count.many": "{n} مقطعاً",
    "vid.parts": "{n} جزء", "vid.parts.zero": "لا أجزاء", "vid.parts.one": "جزء واحد", "vid.parts.two": "جزءان",
    "vid.parts.few": "{n} أجزاء", "vid.parts.many": "{n} جزءاً",
    "vid.source": "المصدر: دار الإسلام (IslamHouse)", "vid.open_source": "افتح في دار الإسلام",
    "vid.loading": "نجهّز قائمة المرئيات من دار الإسلام… (أول مرة فقط)",
    "vid.unavailable": "تعذّر الوصول إلى دار الإسلام الآن. حاول بعد قليل.",
    "vid.empty": "لا توجد مقاطع في هذا الموضوع.",
    "vid.prev": "السابق", "vid.next": "التالي", "vid.page": "صفحة {page} من {pages}",
    "vid.watch": "شاهد", "vid.youtube": "يوتيوب", "vid.by": "إعداد: {names}", "vid.topic": "الموضوع",
    "vid.no_desc": "لا يوجد وصف لهذا المقطع في المصدر.",
    "vid.search": "ابحث في المرئيات", "vid.search_ph": "ابحث بالعنوان أو الوصف أو اسم المُعِد…", "vid.clear": "امسح البحث",
    "vid.results": "{n} نتيجة لـ«{q}»", "vid.results.zero": "لا نتائج لـ«{q}»", "vid.results.one": "نتيجة واحدة لـ«{q}»",
    "vid.results.two": "نتيجتان لـ«{q}»", "vid.results.few": "{n} نتائج لـ«{q}»", "vid.results.many": "{n} نتيجة لـ«{q}»",
    "vid.no_results": "لا توجد مقاطع تطابق «{q}» في هذه اللغة.",
    "vid.lang": "لغة المقاطع", "vid.lang_option": "{name} ({n} مقطع)", "vid.lang_option.one": "{name} (مقطع واحد)",
    "vid.lang_option.two": "{name} (مقطعان)", "vid.lang_option.few": "{name} ({n} مقاطع)", "vid.lang_option.many": "{name} ({n} مقطعاً)",
    "vid.related": "مرئيات ذات صلة من دار الإسلام",
    "vid.related_note": "مقترحة بحسب موضوع سؤالك، والإجابة أعلاه لا تستند إليها.",
    "vid.related_none": "لم أجد في دار الإسلام مقطعاً قريباً من هذا الموضوع بهذه اللغة.", "vid.related_browse": "تصفّح المرئيات",
  },
  en: {
    "nav.videos": "Videos",
    "vid.title": "Videos",
    "vid.lead": "Videos from IslamHouse, one of the sources in the approved scholarly package. They play straight from IslamHouse, exactly as published.",
    "vid.all": "All", "vid.part": "Part {n}",
    "vid.count": "{n} videos", "vid.count.one": "{n} video", "vid.parts": "{n} parts", "vid.parts.one": "{n} part",
    "vid.source": "Source: IslamHouse", "vid.open_source": "Open on IslamHouse",
    "vid.loading": "Preparing the video list from IslamHouse… (first time only)",
    "vid.unavailable": "IslamHouse can't be reached right now. Try again shortly.",
    "vid.empty": "No videos in this topic.",
    "vid.prev": "Previous", "vid.next": "Next", "vid.page": "Page {page} of {pages}",
    "vid.watch": "Watch", "vid.youtube": "YouTube", "vid.by": "By {names}", "vid.topic": "Topic",
    "vid.no_desc": "The source gives no description for this video.",
    "vid.search": "Search videos", "vid.search_ph": "Search by title, description or presenter…", "vid.clear": "Clear search",
    "vid.results": "{n} results for “{q}”", "vid.results.one": "{n} result for “{q}”", "vid.no_results": "No videos match “{q}” in this language.",
    "vid.lang": "Video language", "vid.lang_option": "{name} ({n} videos)", "vid.lang_option.one": "{name} ({n} video)",
    "vid.related": "Related videos from IslamHouse",
    "vid.related_note": "Suggested by the topic of your question; the answer above doesn't rely on them.",
    "vid.related_none": "I couldn't find an IslamHouse video close to this topic in this language.", "vid.related_browse": "Browse videos",
  },
});
