// Calls strings. Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "ref.title": "قبل أن نوصلك بداعية",
    "ref.preparing": "أجهّز ملخصاً لسؤالك…",
    "ref.intro": "هذا ملخص مقترح لسؤالك حتى لا تضطر إلى إعادة شرحه. راجعه وعدّله كما تشاء، ولن يُرسل إلا إذا وافقت.",
    "ref.none": "في هذه التجربة لا يُرسل ملخص. سيسألك الداعية عن سؤالك مباشرة.",
    "ref.question": "سؤالك", "ref.context": "خلفية تريد أن يعرفها الداعية", "ref.explained": "ما شرحه المساعد",
    "ref.unclear": "ما زال غير واضح لك", "ref.remove": "حذف",
    "ref.consent": "أوافق على مشاركة هذا الملخص مع الداعية الذي يقبل طلبي.",
    "ref.share": "شارك الملخص واطلب الاتصال", "ref.skip": "اطلب الاتصال دون ملخص",
    "ref.private": "لا نجمع اسمك أو رقمك. احذف من الملخص أي معلومة لا تريد مشاركتها.",
    "ref.model": "مقترح بالذكاء الاصطناعي", "ref.template": "ملخص بقالب ثابت",
    "talk.title": "تحدّث مع داعية",
    "talk.lead": "اتصال صوتي مباشر بداعية يتحدث لغتك، دون حاجة لسؤال المساعد أولاً. لا نطلب رقمك، ولا تُسجّل المكالمة.",
    "talk.lang": "بأي لغة تريد أن تتحدث؟", "talk.available": "{n} متاح الآن", "talk.none": "لا أحد متاح الآن",
    "talk.gender": "تفضيل الداعية", "talk.any": "أي داعية", "talk.male": "داعية (رجل)", "talk.female": "داعية (امرأة)",
    "talk.call": "اطلب الاتصال الآن", "talk.with_card": "سيُشارك ملخص سؤالك الذي وافقت عليه مع الداعية.",
    "talk.waiting": "نبحث عن داعية متاح بلغتك…", "talk.queue": "قبلك في الانتظار: {n}", "talk.cancel": "إلغاء الطلب",
    "talk.expired": "لم يتوفر داعية خلال وقت الانتظار. يمكنك المحاولة مرة أخرى أو ترك سؤالك في المجموعات.",
    "talk.connected_with": "أنت تتحدث مع {name}", "talk.connecting": "جارٍ الاتصال…", "talk.connected": "متصل",
    "talk.peer_left": "انقطع اتصال الطرف الآخر، ننتظر عودته…", "talk.no_mic": "لم نتمكن من استخدام الميكروفون. يمكنك المتابعة بالكتابة.",
    "talk.failed": "تعذر الاتصال الصوتي على هذه الشبكة. تابع بالكتابة هنا.",
    "talk.mute": "كتم", "talk.unmute": "إلغاء الكتم", "talk.end": "إنهاء", "talk.chat": "رسائل نصية",
    "talk.chat_ph": "اكتب رسالة…", "talk.ended": "انتهت المكالمة", "talk.rate": "كيف كانت المحادثة؟",
    "talk.rated": "شكراً لتقييمك.", "talk.rate_n": "التقييم {n} من 5", "talk.refused": "تعذر الدخول إلى المكالمة.", "talk.back_ask": "عودة إلى الأسئلة", "talk.again": "اتصال جديد",
    "talk.safety": "إن شعرت بعدم الارتياح في أي لحظة، أنهِ المكالمة. لا تشارك معلومات شخصية لا تريد مشاركتها.",
    "talk.you": "أنت", "talk.daai": "الداعية", "talk.seeker": "السائل",
    "dc.tab": "الاتصالات",
    "dc.queue": "طلبات الاتصال", "dc.queue_empty": "لا توجد طلبات الآن. فعّل حالة «متاح» لتصلك الطلبات بلغاتك.",
    "dc.waiting": "ينتظر منذ {s}", "dc.card": "ملخص مرفق", "dc.no_card": "بلا ملخص", "dc.accept": "قبول",
    "dc.taken": "قبل داعية آخر هذا الطلب.", "dc.active": "مكالمتك الحالية",
    "dc.card_title": "ملخص السؤال (بموافقة السائل)", "dc.no_card_long": "لم يشارك السائل ملخصاً. اسأله عن سؤاله بلطف.",
    "dc.question": "السؤال", "dc.context": "الخلفية", "dc.explained": "ما شرحه المساعد", "dc.unclear": "ما زال غير واضح",
    "dc.understood": "فهمتُ السؤال", "dc.understood_done": "سُجّل وقت الفهم",
    "dc.end": "إنهاء المكالمة", "dc.feedback": "قبل أن تنهي", "dc.reexplain": "هل احتجت أن يعيد السائل شرح خلفيته؟",
    "dc.accurate": "هل كان الملخص دقيقاً؟", "dc.na": "لا ينطبق", "dc.note": "ملاحظة (اختياري)", "dc.submit": "حفظ وإنهاء",
    "dc.exp": "تجربة ملخص الإحالة", "dc.exp_on": "التجربة مفعّلة: تتناوب الطلبات بين ملخص النموذج والقالب الثابت وبلا ملخص.",
    "dc.exp_off": "التجربة متوقفة: يُقترح ملخص النموذج دائماً.", "dc.exp_toggle": "تفعيل التجربة",
    "dc.arm.model": "ملخص النموذج", "dc.arm.template": "قالب ثابت", "dc.arm.none": "بلا ملخص", "dc.arm.direct": "اتصال مباشر",
    "dc.calls": "مكالمات", "dc.no_reexplain": "دون إعادة شرح", "dc.accuracy": "دقة الملخص", "dc.median": "وسيط زمن الفهم",
  },
  en: {
    "ref.title": "Before we connect you with a da'i",
    "ref.preparing": "Preparing a summary of your question…",
    "ref.intro": "Here is a suggested summary of your question so you don't have to explain it all again. Review and edit it as you like. It is only sent if you agree.",
    "ref.none": "In this trial no summary is sent. The da'i will ask you about your question directly.",
    "ref.question": "Your question", "ref.context": "Background you want the da'i to know", "ref.explained": "What the assistant explained",
    "ref.unclear": "What is still unclear to you", "ref.remove": "Remove",
    "ref.consent": "I agree to share this summary with the da'i who accepts my request.",
    "ref.share": "Share summary and request a call", "ref.skip": "Request a call without a summary",
    "ref.private": "We don't collect your name or number. Remove anything from the summary you'd rather not share.",
    "ref.model": "Suggested by AI", "ref.template": "Fixed template",
    "talk.title": "Talk with a da'i",
    "talk.lead": "A direct voice call with a guide who speaks your language, no need to ask the assistant first. We don't ask for your number, and calls aren't recorded.",
    "talk.lang": "Which language would you like to speak?", "talk.available": "{n} available now", "talk.none": "No one available now",
    "talk.gender": "Preference", "talk.any": "Any", "talk.male": "Male da'i", "talk.female": "Female da'iyah",
    "talk.call": "Request a call now", "talk.with_card": "The summary you approved will be shared with the da'i.",
    "talk.waiting": "Looking for an available da'i in your language…", "talk.queue": "Ahead of you: {n}", "talk.cancel": "Cancel request",
    "talk.expired": "No da'i became available in time. Try again, or ask in a group.",
    "talk.connected_with": "You're talking with {name}", "talk.connecting": "Connecting…", "talk.connected": "Connected",
    "talk.peer_left": "The other side dropped; waiting for them to come back…", "talk.no_mic": "We couldn't use your microphone. You can continue by text.",
    "talk.failed": "Voice couldn't connect on this network. Continue by text here.",
    "talk.mute": "Mute", "talk.unmute": "Unmute", "talk.end": "End", "talk.chat": "Text messages",
    "talk.chat_ph": "Type a message…", "talk.ended": "Call ended", "talk.rate": "How was the conversation?",
    "talk.rated": "Thank you for rating.", "talk.rate_n": "Rate {n} out of 5", "talk.refused": "Couldn't join the call.", "talk.back_ask": "Back to questions", "talk.again": "New call",
    "talk.safety": "If you feel uncomfortable at any point, end the call. Don't share personal details you'd rather keep private.",
    "talk.you": "You", "talk.daai": "Da'i", "talk.seeker": "Seeker",
    "dc.tab": "Calls",
    "dc.queue": "Call requests", "dc.queue_empty": "No requests right now. Switch to Available to receive requests in your languages.",
    "dc.waiting": "waiting {s}", "dc.card": "Summary attached", "dc.no_card": "No summary", "dc.accept": "Accept",
    "dc.taken": "Another da'i took this request.", "dc.active": "Your current call",
    "dc.card_title": "Question summary (shared by the seeker)", "dc.no_card_long": "The seeker didn't share a summary. Kindly ask about their question.",
    "dc.question": "Question", "dc.context": "Background", "dc.explained": "What the assistant explained", "dc.unclear": "Still unclear",
    "dc.understood": "I understand the question", "dc.understood_done": "Time to understand recorded",
    "dc.end": "End call", "dc.feedback": "Before you finish", "dc.reexplain": "Did the seeker have to re-explain their background?",
    "dc.accurate": "Was the summary accurate?", "dc.na": "N/A", "dc.note": "Note (optional)", "dc.submit": "Save and finish",
    "dc.exp": "Referral summary experiment", "dc.exp_on": "Experiment on: requests rotate between the AI summary, a fixed template and no summary.",
    "dc.exp_off": "Experiment off: the AI summary is always suggested.", "dc.exp_toggle": "Run the experiment",
    "dc.arm.model": "AI summary", "dc.arm.template": "Fixed template", "dc.arm.none": "No summary", "dc.arm.direct": "Direct call",
    "dc.calls": "calls", "dc.no_reexplain": "no re-explaining", "dc.accuracy": "summary accurate", "dc.median": "median time to understand",
  },
});
