// Calls strings. Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "ref.title": "قبل أن نوصلك بداعية",
    "ref.preparing": "أجهّز ملخصاً لسؤالك…",
    "ref.intro": "هذا ملخص مقترح لسؤالك حتى لا تضطر إلى إعادة شرحه. راجعه وعدّله كما تشاء، ولن يُرسل إلا إذا وافقت.",
    "ref.none": "لا يُرسل ملخص مع هذا الطلب. سيسألك الداعية عن سؤالك مباشرة.",
    "ref.question": "سؤالك", "ref.context": "خلفية تريد أن يعرفها الداعية", "ref.explained": "ما شرحه المساعد",
    "ref.unclear": "ما زال غير واضح لك", "ref.remove": "حذف",
    "ref.consent": "أوافق على مشاركة هذا الملخص مع الداعية الذي يقبل طلبي.",
    "ref.share": "شارك الملخص واطلب الاتصال", "ref.skip": "اطلب الاتصال دون ملخص",
    "ref.private": "لا نجمع اسمك أو رقمك. احذف من الملخص أي معلومة لا تريد مشاركتها.",
    "ref.share_chat": "شارك أيضاً محادثتك مع سَبِيلي بأسئلتها وإجاباتها (الأسئلة: {n}) ليعرف الداعية السياق.",
    "ref.share_chat_hint": "يراها الداعية الذي يقبل طلبك كما هي الآن، دون تعديل، ولا يرى ما تسأله بعد ذلك. إن حذفت المحادثة لاحقاً فلن تظهر له.",
    "ref.model": "مقترح بالذكاء الاصطناعي", "ref.template": "ملخص بقالب ثابت",
    "talk.title": "تحدّث مع داعية",
    "talk.lead": "اتصال صوتي مباشر بداعية يتحدث لغتك، دون حاجة لسؤال المساعد أولاً. لا نطلب رقمك، ولا تُسجّل المكالمة.",
    "talk.lang": "بأي لغة تريد أن تتحدث؟", "talk.available": "{n} متاح الآن", "talk.none": "لا أحد متاح الآن",
    "talk.gender": "تفضيل الداعية", "talk.any": "أي داعية", "talk.male": "داعية (رجل)", "talk.female": "داعية (امرأة)",
    "talk.call": "اطلب الاتصال الآن", "talk.with_card": "سيُشارك ملخص سؤالك الذي وافقت عليه مع الداعية.",
    "talk.with_chat": "سيرى الداعية محادثتك مع سَبِيلي كما وافقت.",
    "talk.waiting": "نبحث عن داعية متاح بلغتك…", "talk.queue": "قبلك في الانتظار: {n}", "talk.cancel": "إلغاء الطلب",
    "talk.expired": "لم يتوفر داعية خلال وقت الانتظار. يمكنك المحاولة مرة أخرى أو ترك سؤالك في المجموعات.",
    "talk.connected_with": "أنت تتحدث مع {name}", "talk.connecting": "جارٍ الاتصال…", "talk.connected": "متصل",
    "talk.peer_left": "انقطع اتصال الطرف الآخر، ننتظر عودته…", "talk.no_mic": "لم نتمكن من استخدام الميكروفون. يمكنك المتابعة بالكتابة.",
    "talk.failed": "تعذر الاتصال الصوتي على هذه الشبكة. تابع بالكتابة هنا.",
    "talk.mute": "كتم", "talk.unmute": "إلغاء الكتم", "talk.end": "إنهاء", "talk.end_again": "اضغط مرة أخرى للإنهاء", "talk.chat": "رسائل نصية",
    "talk.not_sent": "لم تُرسل الرسالة لأن الاتصال لم يجهز بعد. حاول بعد لحظات.",
    "talk.chat_ph": "اكتب رسالة…", "talk.ended": "انتهت المكالمة", "talk.rate": "كيف كانت المحادثة؟",
    "talk.rated": "شكراً لتقييمك.", "talk.rate_n": "التقييم {n} من 5", "talk.refused": "تعذر الدخول إلى المكالمة.", "talk.back_ask": "عودة إلى الأسئلة", "talk.again": "اتصال جديد",
    "talk.safety": "إن شعرت بعدم الارتياح في أي لحظة، أنهِ المكالمة. لا تشارك معلومات شخصية لا تريد مشاركتها.",
    "talk.you": "أنت", "talk.daai": "الداعية", "talk.seeker": "السائل",
    "talk.who": "مع من تريد أن تتحدث؟", "talk.anyone": "أول داعية متاح", "talk.anyone_hint": "أسرع طريقة للاتصال.",
    "talk.online": "متاح الآن", "talk.offline": "غير متاح الآن", "talk.before": "تحدثت معه من قبل",
    "talk.offline_note": "هذا الداعية غير متاح الآن. سيصله طلبك إن عاد خلال وقت الانتظار، أو اختر «أول داعية متاح».",
    "talk.waiting_named": "ننتظر أن يقبل الداعية الذي اخترته…", "talk.again_same": "اتصل بـ{name} مرة أخرى",
    },
  en: {
    "ref.title": "Before we connect you with a da'i",
    "ref.preparing": "Preparing a summary of your question…",
    "ref.intro": "Here is a suggested summary of your question so you don't have to explain it all again. Review and edit it as you like. It is only sent if you agree.",
    "ref.none": "No summary is sent with this request. The da'i will ask you about your question directly.",
    "ref.question": "Your question", "ref.context": "Background you want the da'i to know", "ref.explained": "What the assistant explained",
    "ref.unclear": "What is still unclear to you", "ref.remove": "Remove",
    "ref.consent": "I agree to share this summary with the da'i who accepts my request.",
    "ref.share": "Share summary and request a call", "ref.skip": "Request a call without a summary",
    "ref.private": "We don't collect your name or number. Remove anything from the summary you'd rather not share.",
    "ref.share_chat": "Also share your chat with Sabeeli ({n} questions and answers) so the da'i has the context.",
    "ref.share_chat_hint": "The da'i who accepts sees it exactly as it is now, without edits, and not what you ask afterwards. If you delete the chat later, they no longer see it.",
    "ref.model": "Suggested by AI", "ref.template": "Fixed template",
    "talk.title": "Talk with a da'i",
    "talk.lead": "A direct voice call with a guide who speaks your language, no need to ask the assistant first. We don't ask for your number, and calls aren't recorded.",
    "talk.lang": "Which language would you like to speak?", "talk.available": "{n} available now", "talk.none": "No one available now",
    "talk.gender": "Preference", "talk.any": "Any", "talk.male": "Male da'i", "talk.female": "Female da'iyah",
    "talk.call": "Request a call now", "talk.with_card": "The summary you approved will be shared with the da'i.",
    "talk.with_chat": "The da'i will see your chat with Sabeeli, as you agreed.",
    "talk.waiting": "Looking for an available da'i in your language…", "talk.queue": "Ahead of you: {n}", "talk.cancel": "Cancel request",
    "talk.expired": "No da'i became available in time. Try again, or ask in a group.",
    "talk.connected_with": "You're talking with {name}", "talk.connecting": "Connecting…", "talk.connected": "Connected",
    "talk.peer_left": "The other side dropped; waiting for them to come back…", "talk.no_mic": "We couldn't use your microphone. You can continue by text.",
    "talk.failed": "Voice couldn't connect on this network. Continue by text here.",
    "talk.mute": "Mute", "talk.unmute": "Unmute", "talk.end": "End", "talk.end_again": "Tap again to end", "talk.chat": "Text messages",
    "talk.not_sent": "Message not sent: the connection isn't ready yet. Try again in a moment.",
    "talk.chat_ph": "Type a message…", "talk.ended": "Call ended", "talk.rate": "How was the conversation?",
    "talk.rated": "Thank you for rating.", "talk.rate_n": "Rate {n} out of 5", "talk.refused": "Couldn't join the call.", "talk.back_ask": "Back to questions", "talk.again": "New call",
    "talk.safety": "If you feel uncomfortable at any point, end the call. Don't share personal details you'd rather keep private.",
    "talk.you": "You", "talk.daai": "Da'i", "talk.seeker": "Seeker",
    "talk.who": "Who would you like to talk to?", "talk.anyone": "First available da'i", "talk.anyone_hint": "The quickest way to connect.",
    "talk.online": "Available now", "talk.offline": "Not available now", "talk.before": "You talked before",
    "talk.offline_note": "This da'i isn't available right now. Your request reaches them if they come back while you wait, or choose \"First available da'i\".",
    "talk.waiting_named": "Waiting for the da'i you chose to accept…", "talk.again_same": "Call {name} again",
    },
});

// Booked calls (Talk page "Book a time" and "My bookings", the reminder banner).
register({
  ar: {
    "talk.modes": "طريقة التواصل", "talk.mode_now": "اتصل الآن", "talk.mode_book": "احجز موعدًا", "talk.mode_mine": "مواعيدي",
    "book.lead": "اختر وقتًا يناسبك من مواعيد الدعاة. يُؤكَّد الحجز فورًا، ويمكنك إلغاؤه قبل موعده.",
    "book.who": "مع من تريد أن تتحدث؟", "book.anyone": "أي داعية متاح", "book.anyone_hint": "نعرض كل الأوقات المتاحة ونختار لك داعية متفرغًا فيها.",
    "book.next": "أقرب موعد: {when}", "book.full": "لا مواعيد متاحة حاليًا",
    "book.length": "مدة المكالمة", "book.minutes": "{n} دقيقة",
    "book.sixty_hint": "تظهر الأوقات التي يتفرغ فيها الداعية ساعة كاملة.",
    "book.pick_day": "اختر اليوم والوقت", "book.zone_note": "الأوقات بتوقيتك: {zone}", "book.zone": "المنطقة الزمنية",
    "book.morning": "صباحًا", "book.afternoon": "بعد الظهر", "book.evening": "مساءً",
    "book.none": "لا توجد مواعيد متاحة بهذه الاختيارات خلال الأسبوعين القادمين. جرّب لغة أو داعية آخر، أو اتصل الآن.",
    "book.review": "راجع موعدك", "book.lang": "اللغة", "book.with": "مع", "book.when": "الموعد",
    "book.note": "ما الذي تريد الحديث عنه؟", "book.note_ph": "مثلاً: أسئلة عن الصلاة",
    "book.note_hint": "يراه الداعية قبل المكالمة. لا تكتب اسمك أو رقمك أو أي معلومة شخصية.",
    "book.rules": "يُؤكَّد الحجز فورًا. يمكنك الإلغاء قبل الموعد. يُفتح زر الانضمام قبل الموعد بخمس دقائق، وإن لم يحضر أحد الطرفين خلال عشر دقائق يُعدّ الموعد فائتًا.",
    "book.confirm": "تأكيد الحجز", "book.booking": "جارٍ الحجز…",
    "book.taken": "حُجز هذا الوقت للتو. اختر وقتًا آخر.",
    "book.done_title": "تم الحجز", "book.done_toast": "تم تأكيد موعدك.",
    "book.done_hint": "ستجد الموعد في «مواعيدي»، وسيظهر لك تنبيه في الموقع قبل بدايته. أضفه إلى تقويمك ليذكّرك.",
    "book.my": "مواعيدي", "book.another": "احجز موعدًا آخر", "book.new": "موعد جديد",
    "book.need_account": "الحجز يحتاج إلى حساب مجاني (اسم مستخدم وكلمة مرور فقط) حتى تجد موعدك على أي جهاز.",
    "book.add_cal": "أضف إلى التقويم:", "book.ics": "Apple / Outlook",
    "book.cal_title": "مكالمة مع {name} في سَبِيلي", "book.cal_details": "افتح الرابط قبل الموعد بخمس دقائق واضغط «انضم».",
    "book.upcoming": "مواعيدك القادمة", "book.past": "المواعيد السابقة",
    "book.empty": "ليس لديك مواعيد قادمة.", "book.max": "يمكنك حجز {n} مواعيد قادمة كحد أقصى. ألغِ موعدًا لتحجز غيره.",
    "book.with_name": "مع {name}", "book.topic": "الموضوع", "book.daai_said": "رسالة الداعية",
    "book.join": "انضم الآن", "book.join_at": "يُفتح الانضمام الساعة {time}",
    "book.cancel": "إلغاء الموعد", "book.cancel_q": "إلغاء هذا الموعد؟", "book.cancel_yes": "نعم، ألغِه", "book.keep": "إبقاء الموعد",
    "book.cancelled": "أُلغي الموعد.", "book.again": "احجز موعدًا جديدًا",
    "book.st_booked": "مؤكد", "book.st_done": "تمت المكالمة", "book.st_missed_daai": "لم يتمكن الداعية من الحضور",
    "book.st_missed_you": "فاتك الموعد", "book.st_cancel_you": "ألغيته", "book.st_cancel_daai": "ألغاه الداعية",
    "book.st_cancel_system": "أُلغي لأن الداعية لم يعد متاحًا",
    "book.room_early": "يُفتح الانضمام الساعة {time}. ابقَ في هذه الصفحة.", "book.room_wait": "أنت في الانتظار، سيبدأ {name} المكالمة بعد قليل…",
    "book.room_hint": "أبقِ الصفحة مفتوحة. ستبدأ المكالمة تلقائيًا عندما يبدأها الداعية.",
    "book.room_missed": "نعتذر، لم يتمكن الداعية من الحضور. يمكنك الاتصال الآن بأول داعية متاح أو حجز موعد آخر.",
    "book.banner": "مكالمتك مع {name} الساعة {time}", "book.banner_now": "حان موعد مكالمتك مع {name}",
    "err.sign in to book": "سجّل الدخول لتحجز موعدًا.", "err.too many bookings": "وصلت إلى الحد الأقصى من المواعيد القادمة.",
    "err.you already have a booking then": "لديك موعد آخر في هذا الوقت.", "err.slot taken": "حُجز هذا الوقت للتو. اختر وقتًا آخر.",
    "err.not time yet": "لم يحن الوقت بعد.", "err.can't cancel now": "لا يمكن الإلغاء الآن.",
    "err.finish your current call first": "أنهِ مكالمتك الحالية أولاً.",
  },
  en: {
    "talk.modes": "How to connect", "talk.mode_now": "Call now", "talk.mode_book": "Book a time", "talk.mode_mine": "My bookings",
    "book.lead": "Pick a time that suits you from the da'is' schedules. Bookings are confirmed straight away, and you can cancel before the start.",
    "book.who": "Who would you like to talk to?", "book.anyone": "Any available da'i", "book.anyone_hint": "See every free time; we'll pick a da'i who is free then.",
    "book.next": "Next free: {when}", "book.full": "No free times right now",
    "book.length": "Call length", "book.minutes": "{n} minutes",
    "book.sixty_hint": "Showing times when the da'i is free for a full hour.",
    "book.pick_day": "Pick a day and time", "book.zone_note": "Times are in your time zone: {zone}", "book.zone": "Time zone",
    "book.morning": "Morning", "book.afternoon": "Afternoon", "book.evening": "Evening",
    "book.none": "No free times with these choices in the next two weeks. Try another language or da'i, or call now.",
    "book.review": "Review your booking", "book.lang": "Language", "book.with": "With", "book.when": "When",
    "book.note": "What would you like to talk about?", "book.note_ph": "e.g. questions about prayer",
    "book.note_hint": "The da'i sees this before the call. Don't include your name, number or other personal details.",
    "book.rules": "Confirmed straight away. You can cancel before the start. Join opens 5 minutes before; if either side doesn't come within 10 minutes, the booking counts as missed.",
    "book.confirm": "Confirm booking", "book.booking": "Booking…",
    "book.taken": "That time was just taken. Please pick another.",
    "book.done_title": "You're booked", "book.done_toast": "Your booking is confirmed.",
    "book.done_hint": "You'll find it under My bookings, and the site shows a reminder before it starts. Add it to your calendar to get a reminder there too.",
    "book.my": "My bookings", "book.another": "Book another time", "book.new": "New booking",
    "book.need_account": "Booking needs a free account (just a username and password) so you can find your booking on any device.",
    "book.add_cal": "Add to calendar:", "book.ics": "Apple / Outlook",
    "book.cal_title": "Call with {name} on Sabeeli", "book.cal_details": "Open the link 5 minutes before the start and press Join.",
    "book.upcoming": "Upcoming bookings", "book.past": "Past bookings",
    "book.empty": "You have no upcoming bookings.", "book.max": "You can hold up to {n} upcoming bookings. Cancel one to book another.",
    "book.with_name": "With {name}", "book.topic": "Topic", "book.daai_said": "Message from the da'i",
    "book.join": "Join now", "book.join_at": "Join opens at {time}",
    "book.cancel": "Cancel booking", "book.cancel_q": "Cancel this booking?", "book.cancel_yes": "Yes, cancel it", "book.keep": "Keep it",
    "book.cancelled": "Booking cancelled.", "book.again": "Book a new time",
    "book.st_booked": "Confirmed", "book.st_done": "Completed", "book.st_missed_daai": "The da'i couldn't make it",
    "book.st_missed_you": "Missed", "book.st_cancel_you": "You cancelled", "book.st_cancel_daai": "Cancelled by the da'i",
    "book.st_cancel_system": "Cancelled: the da'i is no longer available",
    "book.room_early": "Join opens at {time}. Stay on this page.", "book.room_wait": "You're in. {name} will start the call shortly…",
    "book.room_hint": "Keep this page open. The call starts by itself when the da'i starts it.",
    "book.room_missed": "Sorry, the da'i couldn't make it. You can call the first available da'i now or book another time.",
    "book.banner": "Your call with {name} is at {time}", "book.banner_now": "It's time for your call with {name}",
    "err.sign in to book": "Sign in to book a time.", "err.too many bookings": "You've reached the limit of upcoming bookings.",
    "err.you already have a booking then": "You already have a booking at that time.", "err.slot taken": "That time was just taken. Please pick another.",
    "err.not time yet": "It isn't time yet.", "err.can't cancel now": "This can't be cancelled now.",
    "err.finish your current call first": "Finish your current call first.",
  },
});
