// Calls strings. Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "ref.title": "قبل أن نوصلك بداعية",
    "ref.preparing": "أجهّز ملخصاً لسؤالك…",
    "ref.intro": "هذا ملخص مقترح لسؤالك حتى لا تضطر إلى إعادة شرحه. راجعه وعدّله كما تشاء، ولن يُرسل إلا إذا وافقت.",
    "ref.none": "في هذه التجربة لا يُرسل ملخص. سيسألك الداعية عن سؤالك مباشرة.",
    "ref.question": "سؤالك", "ref.context": "خلفية تريد أن يعرفها الداعية", "ref.explained": "ما شرحه المساعد",
    "ref.unclear": "ما زال غير واضح لك", "ref.remove": "حذف",
    "ref.consent": "أوافق على مشاركة هذا الملخص مع الداعية الذي يقبل طلبي.",
    "ref.share": "شارك الملخص واطلب الاتصال", "ref.skip": "اطلب الاتصال دون ملخص",
    "ref.private": "لا نجمع اسمك أو رقمك. احذف من الملخص أي معلومة لا تريد مشاركتها.",
    "ref.share_chat": "شارك أيضاً محادثتك مع سَبِيلي بأسئلتها وإجاباتها (الأسئلة: {n}) ليعرف الداعية السياق.",
    "ref.share_chat_hint": "يراها الداعية الذي يقبل طلبك كما هي الآن، دون تعديل، ولا يرى ما تسأله بعد ذلك. إن حذفت المحادثة لاحقاً فلن تظهر له.",
    "ref.model": "مقترح بالذكاء الاصطناعي", "ref.template": "ملخص بقالب ثابت",
    "talk.title": "تحدّث مع داعية",
    "talk.lead": "اتصال صوتي مباشر بداعية يتحدث لغتك، دون حاجة لسؤال المساعد أولاً. لا نطلب رقمك، ولا تُسجّل المكالمة.",
    "talk.lang": "بأي لغة تريد أن تتحدث؟", "talk.available": "{n} متاح الآن", "talk.none": "لا أحد متاح الآن",
    "talk.gender": "تفضيل الداعية", "talk.any": "أي داعية", "talk.male": "داعية (رجل)", "talk.female": "داعية (امرأة)",
    "talk.call": "اطلب الاتصال الآن", "talk.with_card": "سيُشارك ملخص سؤالك الذي وافقت عليه مع الداعية.",
    "talk.with_chat": "سيرى الداعية محادثتك مع سَبِيلي كما وافقت.",
    "talk.waiting": "نبحث عن داعية متاح بلغتك…", "talk.queue": "قبلك في الانتظار: {n}", "talk.cancel": "إلغاء الطلب",
    "talk.expired": "لم يتوفر داعية خلال وقت الانتظار. يمكنك المحاولة مرة أخرى أو ترك سؤالك في المجموعات.",
    "talk.connected_with": "أنت تتحدث مع {name}", "talk.connecting": "جارٍ الاتصال…", "talk.connected": "متصل",
    "talk.peer_left": "انقطع اتصال الطرف الآخر، ننتظر عودته…", "talk.no_mic": "لم نتمكن من استخدام الميكروفون. يمكنك المتابعة بالكتابة.",
    "talk.failed": "تعذر الاتصال الصوتي على هذه الشبكة. تابع بالكتابة هنا.",
    "talk.mute": "كتم", "talk.unmute": "إلغاء الكتم", "talk.end": "إنهاء", "talk.chat": "رسائل نصية",
    "talk.chat_ph": "اكتب رسالة…", "talk.ended": "انتهت المكالمة", "talk.rate": "كيف كانت المحادثة؟",
    "talk.rated": "شكراً لتقييمك.", "talk.rate_n": "التقييم {n} من 5", "talk.refused": "تعذر الدخول إلى المكالمة.", "talk.back_ask": "عودة إلى الأسئلة", "talk.again": "اتصال جديد",
    "talk.safety": "إن شعرت بعدم الارتياح في أي لحظة، أنهِ المكالمة. لا تشارك معلومات شخصية لا تريد مشاركتها.",
    "talk.you": "أنت", "talk.daai": "الداعية", "talk.seeker": "السائل",
    "talk.who": "مع من تريد أن تتحدث؟", "talk.anyone": "أول داعية متاح", "talk.anyone_hint": "أسرع طريقة للاتصال.",
    "talk.online": "متاح الآن", "talk.offline": "غير متاح الآن", "talk.before": "تحدثت معه من قبل",
    "talk.offline_note": "هذا الداعية غير متاح الآن. سيصله طلبك إن عاد خلال وقت الانتظار، أو اختر «أول داعية متاح».",
    "talk.waiting_named": "ننتظر أن يقبل الداعية الذي اخترته…", "talk.again_same": "اتصل بـ{name} مرة أخرى",
    },
  en: {
    "ref.title": "Before we connect you with a da'i",
    "ref.preparing": "Preparing a summary of your question…",
    "ref.intro": "Here is a suggested summary of your question so you don't have to explain it all again. Review and edit it as you like. It is only sent if you agree.",
    "ref.none": "In this trial no summary is sent. The da'i will ask you about your question directly.",
    "ref.question": "Your question", "ref.context": "Background you want the da'i to know", "ref.explained": "What the assistant explained",
    "ref.unclear": "What is still unclear to you", "ref.remove": "Remove",
    "ref.consent": "I agree to share this summary with the da'i who accepts my request.",
    "ref.share": "Share summary and request a call", "ref.skip": "Request a call without a summary",
    "ref.private": "We don't collect your name or number. Remove anything from the summary you'd rather not share.",
    "ref.share_chat": "Also share your chat with Sabeeli ({n} questions and answers) so the da'i has the context.",
    "ref.share_chat_hint": "The da'i who accepts sees it exactly as it is now, without edits, and not what you ask afterwards. If you delete the chat later, they no longer see it.",
    "ref.model": "Suggested by AI", "ref.template": "Fixed template",
    "talk.title": "Talk with a da'i",
    "talk.lead": "A direct voice call with a guide who speaks your language, no need to ask the assistant first. We don't ask for your number, and calls aren't recorded.",
    "talk.lang": "Which language would you like to speak?", "talk.available": "{n} available now", "talk.none": "No one available now",
    "talk.gender": "Preference", "talk.any": "Any", "talk.male": "Male da'i", "talk.female": "Female da'iyah",
    "talk.call": "Request a call now", "talk.with_card": "The summary you approved will be shared with the da'i.",
    "talk.with_chat": "The da'i will see your chat with Sabeeli, as you agreed.",
    "talk.waiting": "Looking for an available da'i in your language…", "talk.queue": "Ahead of you: {n}", "talk.cancel": "Cancel request",
    "talk.expired": "No da'i became available in time. Try again, or ask in a group.",
    "talk.connected_with": "You're talking with {name}", "talk.connecting": "Connecting…", "talk.connected": "Connected",
    "talk.peer_left": "The other side dropped; waiting for them to come back…", "talk.no_mic": "We couldn't use your microphone. You can continue by text.",
    "talk.failed": "Voice couldn't connect on this network. Continue by text here.",
    "talk.mute": "Mute", "talk.unmute": "Unmute", "talk.end": "End", "talk.chat": "Text messages",
    "talk.chat_ph": "Type a message…", "talk.ended": "Call ended", "talk.rate": "How was the conversation?",
    "talk.rated": "Thank you for rating.", "talk.rate_n": "Rate {n} out of 5", "talk.refused": "Couldn't join the call.", "talk.back_ask": "Back to questions", "talk.again": "New call",
    "talk.safety": "If you feel uncomfortable at any point, end the call. Don't share personal details you'd rather keep private.",
    "talk.you": "You", "talk.daai": "Da'i", "talk.seeker": "Seeker",
    "talk.who": "Who would you like to talk to?", "talk.anyone": "First available da'i", "talk.anyone_hint": "The quickest way to connect.",
    "talk.online": "Available now", "talk.offline": "Not available now", "talk.before": "You talked before",
    "talk.offline_note": "This da'i isn't available right now. Your request reaches them if they come back while you wait, or choose \"First available da'i\".",
    "talk.waiting_named": "Waiting for the da'i you chose to accept…", "talk.again_same": "Call {name} again",
    },
});
