// Strings for the da'i console (calls tab, groups and meetups tabs). Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "dai.title": "لوحة الداعية",
    "dai.user": "اسم المستخدم",
    "dai.available": "متاح لاستقبال المكالمات", "dai.logout": "تسجيل الخروج", "dai.langs": "لغاتك: {l}",
    "dai.logout_q": "تسجيل الخروج يُنهي مكالمتك الحالية.", "dai.logout_keep": "البقاء في المكالمة",
    "dai.session_ended": "انتهت جلستك. سجّل الدخول مرة أخرى.",
    "dc.tab": "الاتصالات",
    "dc.queue": "طلبات الاتصال",
    "dc.queue_empty": "لا توجد طلبات الآن. ستظهر هنا الطلبات الجديدة بلغاتك.",
    "dc.queue_off": "لا توجد طلبات الآن. فعّل حالة «متاح» لتصلك الطلبات بلغاتك.",
    "dc.waiting_n": "{n} طلب بالانتظار", "dc.waiting_n.one": "طلب واحد بالانتظار", "dc.waiting_n.two": "طلبان بالانتظار",
    "dc.waiting_n.few": "{n} طلبات بالانتظار", "dc.waiting_n.many": "{n} طلباً بالانتظار",
    "dc.waiting": "ينتظر منذ {s}",
    "dc.card": "ملخص مرفق",
    "dc.no_card": "بلا ملخص",
    "dc.accept": "قبول", "dc.accepting": "جارٍ القبول…",
    "dc.taken": "قبل داعية آخر هذا الطلب.",
    "dc.active": "مكالمتك الحالية",
    "dc.card_title": "ملخص السؤال (بموافقة السائل)",
    "dc.no_card_long": "لم يشارك السائل ملخصاً. اسأله عن سؤاله بلطف.",
    "dc.question": "السؤال",
    "dc.context": "الخلفية",
    "dc.explained": "ما شرحه المساعد",
    "dc.unclear": "ما زال غير واضح",
    "dc.understood": "فهمتُ السؤال",
    "dc.understood_done": "سُجّل وقت الفهم",
    "dc.end": "إنهاء المكالمة",
    "dc.feedback": "قبل أن تنهي",
    "dc.reexplain": "هل احتجت أن يعيد السائل شرح خلفيته؟",
    "dc.accurate": "هل كان الملخص دقيقاً؟",
    "dc.na": "لا ينطبق",
    "dc.note": "ملاحظة (اختياري)",
    "dc.submit": "حفظ وإنهاء", "dc.saved": "شكراً، حُفظت ملاحظاتك.",
    "dc.exp": "مقارنة طرق الإحالة",
    "dc.exp_on": "المقارنة مفعّلة: تتناوب الطلبات بين ملخص النموذج والقالب الثابت وبلا ملخص.",
    "dc.exp_off": "المقارنة متوقفة: يُقترح ملخص النموذج دائماً.",
    "dc.exp_toggle": "تشغيل المقارنة",
    "dc.arm.model": "ملخص النموذج",
    "dc.arm.template": "قالب ثابت",
    "dc.arm.none": "بلا ملخص",
    "dc.arm.direct": "اتصال مباشر",
    "dc.calls_one": "مكالمة واحدة", "dc.calls_two": "مكالمتان", "dc.calls_few": "{n} مكالمات", "dc.calls_many": "{n} مكالمة",
    "dc.no_reexplain": "دون إعادة شرح",
    "dc.accuracy": "دقة الملخص",
    "dc.median": "وسيط زمن الفهم",
    "dg.tab": "المجموعات",
    "dm.tab": "الفعاليات",
    "dg.groups": "مجموعاتي",
    "dg.new": "مجموعة جديدة",
    "dg.open": "إدارة",
    "dg.flags": "{n} بانتظار توضيحك",
    "dg.empty": "لا تقود أي مجموعة بعد.",
    "dg.title": "العنوان",
    "dg.desc": "وصف قصير",
    "dg.lang": "اللغة",
    "dg.city": "المدينة",
    "dg.country": "الدولة",
    "dg.audience": "الفئة",
    "dg.create": "إنشاء", "dg.created": "أُنشئت المجموعة.",
    "dg.post_ph": "اكتب رسالة للمجموعة بصفتك القائد…", "dg.post_label": "رسالة إلى المجموعة",
    "dg.no_messages": "لا توجد رسائل بعد. اكتب أول رسالة للمجموعة.",
    "dg.delete": "حذف", "dg.delete_q": "حذف هذه الرسالة للجميع؟", "dg.deleted_ok": "حُذفت الرسالة.",
    "dg.mute": "كتم العضو", "dg.mute_q": "كتم هذا العضو؟ يبقى في المجموعة ويقرأ، لكنه لا يستطيع النشر.",
    "dg.muted_ok": "تم كتم العضو.", "dg.muted": "مكتوم", "dg.unmute": "إلغاء الكتم", "dg.unmuted_ok": "أُلغي الكتم، ويستطيع العضو النشر من جديد.",
    "dg.resolve": "تأكيد التوضيح",
    "dg.back": "كل مجموعاتي",
    "dm.meetups": "فعالياتي",
    "dm.new": "فعالية جديدة",
    "dm.empty": "لا توجد فعاليات بعد.",
    "dm.attendees": "الحضور ({n})",
    "dm.cancel": "إلغاء الفعالية", "dm.cancel_q": "إلغاء هذه الفعالية؟ سيفقد من حجزوا أماكنهم.", "dm.keep": "إبقاء الفعالية",
    "dm.cancel_done": "أُلغيت الفعالية.",
    "dm.cancelled": "ملغاة", "dm.ended": "انتهت",
    "dm.venue": "المكان (مكان عام)",
    "dm.when": "الموعد",
    "dm.duration": "المدة بالدقائق",
    "dm.capacity": "العدد الأقصى",
    "dm.public": "أؤكد أن المكان عام (مركز، مسجد، مكتبة، قاعة عامة).",
    "dm.create": "نشر الفعالية", "dm.created": "نُشرت الفعالية.",
    "dm.group": "ربط بمجموعة (اختياري)",
    "dm.none": "بلا",
    "dm.kind": "طريقة الحضور", "dm.kind_required": "يحجز الحاضر مقعداً باسم مستعار ويحصل على رمز حجز.",
    "dm.kind_required_online": "يحجز الحاضر مقعداً باسم مستعار، ثم يظهر له رابط اللقاء.",
    "dm.kind_open": "لا حجز: تظهر الفعالية للجميع ويحضرها من شاء مباشرة.",
    "dm.kind_open_online": "دون حدّ للعدد: يضغط الحاضر «انضمام» فيظهر له رابط اللقاء.", "dm.capacity_open": "العدد المتوقع",
    "dm.series": "السلسلة (اختياري)", "dm.kids_note": "فعاليات الأطفال يحضرها الطفل مع ولي أمره، ويؤكد ولي الأمر ذلك عند الحجز.",
    "dl.tab": "سجل المكالمات", "dl.title": "مكالماتي في {m}", "dl.month": "الشهر", "dl.calls": "مكالمة رددتُ عليها", "dl.minutes": "دقيقة حوار",
    "dl.no_reexplain": "إحالة دون إعادة شرح", "dl.of": "{a} من {b}", "dl.rating": "متوسط تقييم السائلين",
    "dl.privacy": "يُحفظ هنا ما يلزم لقياس جودة الإحالة من أرقام فقط. لا يُسجَّل صوت المكالمة، ولا يظهر ما يدل على هوية السائل. ولا تظهر محادثة السائل مع سَبِيلي إلا إذا اختار مشاركتها معك.",
    "dl.empty": "لا توجد مكالمات رددتَ عليها في هذا الشهر.", "dl.when": "التاريخ والوقت", "dl.lang": "اللغة", "dl.length": "المدة",
    "dl.arm": "نوع الإحالة", "dl.understood": "فهمت السؤال بعد", "dl.reexplain": "أعاد الشرح؟", "dl.accurate": "الملخص دقيق؟",
    "dl.stars": "التقييم", "dl.note": "ملاحظتي",
    "dl.chat": "المحادثة المشتركة", "dl.chat_show": "اعرضها", "dl.chat_gone": "حذف السائل هذه المحادثة، فلم تعد متاحة.",
    "dp.tab": "ملفي الشخصي", "dp.edit": "بياناتي", "dp.titled_m": "الداعية {n}", "dp.titled_f": "الداعية {n}",
    "dp.name": "الاسم بالعربية", "dp.name_en": "الاسم بالإنجليزية", "dp.langs": "لغاتي",
    "dp.langs_hint": "يصلك طلب الاتصال فقط من سائل يختار إحدى لغاتك.", "dp.one_lang": "اختر لغة واحدة على الأقل.",
    "dp.bio": "نبذة بالعربية", "dp.bio_en": "نبذة بالإنجليزية", "dp.count": "{n} من {max}",
    "dp.save": "حفظ", "dp.saving": "جارٍ الحفظ…", "dp.saved": "حُفظ ملفك.", "dp.reset": "تجاهل التعديلات",
    "dp.invalid": "تأكد من الاسم ومن اختيار لغة واحدة على الأقل.", "dp.preview": "هكذا يراك السائل", "dp.no_bio": "لا توجد نبذة بعد.",
    "dp.gender": "أنا", "dp.gender_m": "داعية (رجل)", "dp.gender_f": "داعية (امرأة)", "dp.country": "الدولة", "dp.city": "المدينة",
    "dc.for_you": "طلبك بالاسم",
    "dc.chat_badge": "شارك محادثته", "dc.chat_title": "محادثة السائل مع سَبِيلي", "dc.chat_count": "(الأسئلة: {n})",
    "dc.chat_hint": "شاركها السائل بموافقته كما كانت عند طلب الاتصال. الإجابات من المصادر المعتمدة كما رآها.",
    "dc.seeker_asked": "سأل:", "dc.photo": "أرفق صورة", "dc.chat_show": "اعرض المحادثة كاملة",
    "da.tab": "حسابات الدعاة", "da.langs": "لغاته", "da.gender": "الداعية", "da.add": "أضف داعية", "da.do_add": "أضف الحساب", "da.added": "أُضيف الحساب {u}.",
    "da.user_hint": "حروف إنجليزية صغيرة وأرقام و _ أو . (٣ إلى ٣٢).", "da.first_password": "كلمة مرور أولى",
    "da.pass_hint": "٨ أحرف على الأقل. أرسلها للداعية بطريقة آمنة.",
    "da.list": "الدعاة والمراجعون", "da.list_lead": "الحساب الموقوف لا يستطيع الدخول ولا يظهر للسائلين. تغيير كلمة المرور يُخرج الداعية من كل أجهزته.",
    "da.reviewer": "مراجع", "da.disabled": "موقوف", "da.disable": "أوقف", "da.enable": "فعّل",
    "da.disabled_done": "أُوقف الحساب.", "da.enabled_done": "فُعّل الحساب.",
    "da.disable_q": "إيقاف هذا الحساب؟ لن يستطيع صاحبه الدخول، ولن يظهر للسائلين.",
    "da.reset": "كلمة مرور جديدة", "da.new_password": "كلمة المرور الجديدة", "da.reset_done": "تغيّرت كلمة المرور.", "da.reset_self_done": "تغيّرت كلمة مرورك. ادخل بها من جديد.",
    "da.invalid": "تأكد من اسم المستخدم والاسم وكلمة المرور (٨ أحرف على الأقل).",
    "da.err.username taken": "اسم المستخدم مأخوذ.", "da.err.you can't disable your own account": "لا يمكنك إيقاف حسابك.",
    "nm.button": "أسلم في هذه المكالمة؟", "nm.button_short": "سجّل إسلامه", "nm.after_call": "هل أسلم السائل في هذه المكالمة؟",
    "nm.confirm_title": "تأكيد إسلام السائل", "nm.confirm_q": "هل نطق السائل بالشهادتين معك في هذه المكالمة؟",
    "nm.confirm_note": "سنسأله أولاً إن كان يحب أن تُشارَك البشرى في مجموعاته. لا يُعلَن شيء ولا يظهر وسم «مسلم جديد» دون موافقته، وإن رفض يُحذف هذا التسجيل.",
    "nm.confirm_yes": "نعم، أسلم", "nm.already_shared": "سبق أن شارك السائل هذه البشرى مع مجموعاته.", "nm.done": "سُجّل. سنسأل السائل إن كان يحب مشاركة البشرى.",
    "nm.badge_pending": "سجّلتَ إسلامه: بانتظار رأيه في المشاركة", "nm.badge_pending_short": "بانتظار رأيه",
    "nm.badge_shared": "أسلم وشارك البشرى مع مجموعاته", "nm.badge_shared_short": "شارك البشرى",
    "nm.undo": "تراجع", "nm.undo_late": "أجاب السائل بالفعل، فلا يمكن التراجع.",
    "nm.stat": "أسلموا في مكالماتك", "nm.col": "أسلم",
    // Sliding session and the da'i's own password (Security card on "My profile")
    "dai.relogin_after_call": "انتهى تسجيل دخولك. أكمل مكالمتك، ثم سجّل الدخول من جديد بعد انتهائها.",
    "dp.security": "الأمان", "dp.current_password": "كلمة المرور الحالية", "dp.new_password": "كلمة المرور الجديدة",
    "dp.password_hint": "٨ أحرف على الأقل.", "dp.change_password": "غيّر كلمة المرور", "dp.changing_password": "جارٍ التغيير…",
    "dp.password_changed": "تغيّرت كلمة المرور، وخرجت من حسابك على الأجهزة الأخرى.",
    "dp.password_short": "كلمة المرور الجديدة ٨ أحرف على الأقل.",
    "dp.demo_password": "هذا حساب نموذجي مشترك، فلا تتغير كلمة مروره من هنا.",
    "dp.err.wrong password": "كلمة المرور الحالية غير صحيحة.", "dp.err.too many attempts": "محاولات كثيرة. انتظر عشر دقائق ثم حاول.",
    "dp.err.demo account": "هذا حساب نموذجي مشترك، فلا تتغير كلمة مروره من هنا.",
  },
  en: {
    "nm.button": "Embraced Islam in this call?", "nm.button_short": "Mark as Muslim", "nm.after_call": "Did the seeker embrace Islam in this call?",
    "nm.confirm_title": "Confirm the seeker embraced Islam", "nm.confirm_q": "Did the seeker say the shahada with you in this call?",
    "nm.confirm_note": "We'll first ask them whether they'd like the news shared in their groups. Nothing is announced and no \"new Muslim\" badge appears without their OK, and if they say no, this record is deleted.",
    "nm.confirm_yes": "Yes, they embraced Islam", "nm.already_shared": "The seeker already shared this news with their groups.", "nm.done": "Saved. We'll ask the seeker whether to share the news.",
    "nm.badge_pending": "Marked: waiting for the seeker's choice", "nm.badge_pending_short": "Waiting for them",
    "nm.badge_shared": "Embraced Islam and shared the news with their groups", "nm.badge_shared_short": "News shared",
    "nm.undo": "Undo", "nm.undo_late": "The seeker already answered, so it can't be undone.",
    "nm.stat": "embraced Islam in your calls", "nm.col": "Embraced Islam",
    "dai.title": "Da'i console",
    "dai.user": "Username",
    "dai.available": "Available for calls", "dai.logout": "Sign out", "dai.langs": "Your languages: {l}",
    "dai.logout_q": "Signing out ends your current call.", "dai.logout_keep": "Stay in the call",
    "dai.session_ended": "Your session ended. Sign in again.",
    "dc.tab": "Calls",
    "dc.queue": "Call requests",
    "dc.queue_empty": "No requests right now. New requests in your languages will appear here.",
    "dc.queue_off": "No requests right now. Switch to Available to receive requests in your languages.",
    "dc.waiting_n": "{n} requests waiting", "dc.waiting_n.one": "1 request waiting",
    "dc.waiting": "waiting {s}",
    "dc.card": "Summary attached",
    "dc.no_card": "No summary",
    "dc.accept": "Accept", "dc.accepting": "Accepting…",
    "dc.taken": "Another da'i took this request.",
    "dc.active": "Your current call",
    "dc.card_title": "Question summary (shared by the seeker)",
    "dc.no_card_long": "The seeker didn't share a summary. Kindly ask about their question.",
    "dc.question": "Question",
    "dc.context": "Background",
    "dc.explained": "What the assistant explained",
    "dc.unclear": "Still unclear",
    "dc.understood": "I understand the question",
    "dc.understood_done": "Time to understand recorded",
    "dc.end": "End call",
    "dc.feedback": "Before you finish",
    "dc.reexplain": "Did the seeker have to re-explain their background?",
    "dc.accurate": "Was the summary accurate?",
    "dc.na": "N/A",
    "dc.note": "Note (optional)",
    "dc.submit": "Save and finish", "dc.saved": "Thanks, your notes are saved.",
    "dc.exp": "Referral summary comparison",
    "dc.exp_on": "Comparison on: requests rotate between the AI summary, a fixed template and no summary.",
    "dc.exp_off": "Comparison off: the AI summary is always suggested.",
    "dc.exp_toggle": "Run the comparison",
    "dc.arm.model": "AI summary",
    "dc.arm.template": "Fixed template",
    "dc.arm.none": "No summary",
    "dc.arm.direct": "Direct call",
    "dc.calls_one": "1 call", "dc.calls_two": "2 calls", "dc.calls_few": "{n} calls", "dc.calls_many": "{n} calls",
    "dc.no_reexplain": "no re-explaining",
    "dc.accuracy": "summary accurate",
    "dc.median": "median time to understand",
    "dg.tab": "Groups",
    "dm.tab": "Events",
    "dg.groups": "My groups",
    "dg.new": "New group",
    "dg.open": "Manage",
    "dg.flags": "{n} waiting for you",
    "dg.empty": "You don't lead any group yet.",
    "dg.title": "Title",
    "dg.desc": "Short description",
    "dg.lang": "Language",
    "dg.city": "City",
    "dg.country": "Country",
    "dg.audience": "Audience",
    "dg.create": "Create", "dg.created": "Group created.",
    "dg.post_ph": "Write to the group as its leader…", "dg.post_label": "Message to the group",
    "dg.no_messages": "No messages yet. Write the first one to the group.",
    "dg.delete": "Delete", "dg.delete_q": "Delete this message for everyone?", "dg.deleted_ok": "Message deleted.",
    "dg.mute": "Mute member", "dg.mute_q": "Mute this member? They stay in the group and can read, but can't post.",
    "dg.muted_ok": "Member muted.", "dg.muted": "Muted", "dg.unmute": "Unmute", "dg.unmuted_ok": "Unmuted. The member can post again.",
    "dg.resolve": "Mark as clarified",
    "dg.back": "All my groups",
    "dm.meetups": "My events",
    "dm.new": "New event",
    "dm.empty": "No events yet.",
    "dm.attendees": "Attending ({n})",
    "dm.cancel": "Cancel event", "dm.cancel_q": "Cancel this event? People who booked lose their place.", "dm.keep": "Keep event",
    "dm.cancel_done": "Event cancelled.",
    "dm.cancelled": "Cancelled", "dm.ended": "Ended",
    "dm.venue": "Venue (a public place)",
    "dm.when": "Date and time",
    "dm.duration": "Duration (minutes)",
    "dm.capacity": "Capacity",
    "dm.public": "I confirm the venue is public (a centre, mosque, library or public hall).",
    "dm.create": "Publish event", "dm.created": "Event published.",
    "dm.group": "Link to a group (optional)",
    "dm.none": "None",
    "dm.kind": "How people attend", "dm.kind_required": "Attendees book a spot with a nickname and get a booking code.",
    "dm.kind_required_online": "Attendees book a spot with a nickname, then see the meeting link.",
    "dm.kind_open": "No booking: the event is listed and anyone can just come.",
    "dm.kind_open_online": "No limit on places: people tap Join and then see the meeting link.", "dm.capacity_open": "Expected attendance",
    "dm.series": "Series (optional)", "dm.kids_note": "Children attend with a guardian, who confirms it when booking.",
    "dl.tab": "Call log", "dl.title": "My calls in {m}", "dl.month": "Month", "dl.calls": "calls answered", "dl.minutes": "minutes of conversation",
    "dl.no_reexplain": "referrals with no re-explaining", "dl.of": "{a} of {b}", "dl.rating": "average seeker rating",
    "dl.privacy": "Only the numbers needed to measure referral quality are kept. Call audio is never recorded, and nothing identifies the seeker. A seeker's chat with Sabeeli shows only if they chose to share it with you.",
    "dl.empty": "You didn't answer any calls this month.", "dl.when": "Date and time", "dl.lang": "Language", "dl.length": "Length",
    "dl.arm": "Referral type", "dl.understood": "Understood after", "dl.reexplain": "Re-explained?", "dl.accurate": "Summary accurate?",
    "dl.stars": "Rating", "dl.note": "My note",
    "dl.chat": "Shared chat", "dl.chat_show": "Show", "dl.chat_gone": "The seeker deleted this chat, so it's no longer available.",
    "dp.tab": "My profile", "dp.edit": "My details", "dp.titled_m": "Da'i {n}", "dp.titled_f": "Da'iyah {n}",
    "dp.name": "Name in Arabic", "dp.name_en": "Name in English", "dp.langs": "My languages",
    "dp.langs_hint": "You only receive call requests from seekers who choose one of your languages.", "dp.one_lang": "Choose at least one language.",
    "dp.bio": "Bio in Arabic", "dp.bio_en": "Bio in English", "dp.count": "{n} of {max}",
    "dp.save": "Save", "dp.saving": "Saving…", "dp.saved": "Your profile is saved.", "dp.reset": "Discard changes",
    "dp.invalid": "Check your name and choose at least one language.", "dp.preview": "How seekers see you", "dp.no_bio": "No bio yet.",
    "dp.gender": "I am", "dp.gender_m": "Male da'i", "dp.gender_f": "Female da'iyah", "dp.country": "Country", "dp.city": "City",
    "dc.for_you": "Asked for you",
    "dc.chat_badge": "Chat shared", "dc.chat_title": "The seeker's chat with Sabeeli", "dc.chat_count": "({n} questions)",
    "dc.chat_hint": "Shared by the seeker with their OK, as it was when they asked for the call. The answers are from the approved sources, as they saw them.",
    "dc.seeker_asked": "They asked:", "dc.photo": "Attached a photo", "dc.chat_show": "Show the whole conversation",
    "da.tab": "Da'i accounts", "da.langs": "Languages", "da.gender": "Da'i", "da.add": "Add a da'i", "da.do_add": "Add account", "da.added": "Account {u} added.",
    "da.user_hint": "Lower-case letters, digits, _ or . (3 to 32).", "da.first_password": "First password",
    "da.pass_hint": "At least 8 characters. Send it to the da'i safely.",
    "da.list": "Da'is and reviewers", "da.list_lead": "A disabled account can't sign in and isn't shown to seekers. A new password signs the da'i out on every device.",
    "da.reviewer": "Reviewer", "da.disabled": "Disabled", "da.disable": "Disable", "da.enable": "Enable",
    "da.disabled_done": "Account disabled.", "da.enabled_done": "Account enabled.",
    "da.disable_q": "Disable this account? They won't be able to sign in, and seekers won't see them.",
    "da.reset": "New password", "da.new_password": "New password", "da.reset_done": "Password changed.", "da.reset_self_done": "Your password changed. Sign in with the new one.",
    "da.invalid": "Check the username, the name and the password (at least 8 characters).",
    "da.err.username taken": "That username is taken.", "da.err.you can't disable your own account": "You can't disable your own account.",
    // Sliding session and the da'i's own password (Security card on "My profile")
    "dai.relogin_after_call": "Your sign-in has ended. Finish your call, then sign in again once it's over.",
    "dp.security": "Security", "dp.current_password": "Current password", "dp.new_password": "New password",
    "dp.password_hint": "At least 8 characters.", "dp.change_password": "Change password", "dp.changing_password": "Changing…",
    "dp.password_changed": "Password changed. You were signed out on your other devices.",
    "dp.password_short": "The new password needs at least 8 characters.",
    "dp.demo_password": "This is a shared sample account, so its password can't be changed here.",
    "dp.err.wrong password": "Your current password is wrong.", "dp.err.too many attempts": "Too many attempts. Wait ten minutes and try again.",
    "dp.err.demo account": "This is a shared sample account, so its password can't be changed here.",
  },
});

// "My schedule" tab and booked calls on the calls tab.
register({
  ar: {
    "ds.tab": "مواعيدي",
    "ds.title": "أوقات استقبال الحجوزات",
    "ds.lead": "حدّد الأوقات التي يمكن للسائلين حجز مكالمة معك فيها. يُقسَّم كل وقت إلى مواعيد من 30 دقيقة، ويؤكَّد الحجز تلقائيًا.",
    "ds.taking": "أستقبل حجوزات",
    "ds.paused_note": "الحجوزات متوقفة: لا تظهر أوقاتك للسائلين. المواعيد المحجوزة سابقًا باقية كما هي.",
    "ds.first_time": "لم تحدد أوقاتك بعد. اختر الأيام والساعات ثم احفظ.",
    "ds.tz": "منطقتك الزمنية", "ds.tz_hint": "تُكتب الأوقات بتوقيتك، ويراها كل سائل بتوقيته هو.",
    "ds.slots_note": "يحجز السائل 30 دقيقة، أو ساعة كاملة إن كان الوقت التالي متاحًا. لا يُحجز موعد قبل أقل من ساعتين من بدايته، ولا بعد أكثر من 14 يومًا.",
    "ds.day_sun": "الأحد", "ds.day_mon": "الاثنين", "ds.day_tue": "الثلاثاء", "ds.day_wed": "الأربعاء", "ds.day_thu": "الخميس", "ds.day_fri": "الجمعة", "ds.day_sat": "السبت",
    "ds.closed": "لا مواعيد", "ds.from": "من", "ds.to": "إلى", "ds.remove": "حذف", "ds.add": "إضافة فترة", "ds.copy_all": "نسخ لكل الأيام",
    "ds.days_off": "أيام الإجازة", "ds.days_off_hint": "لن تظهر أوقاتك في هذه الأيام. لا يُلغى أي موعد محجوز تلقائيًا.", "ds.add_off": "إضافة يوم",
    "ds.clash": "لديك مواعيد محجوزة في أيام الإجازة ({n}). ألغِها من القائمة أدناه إن لم تستطع حضورها.",
    "ds.err_order": "يجب أن تنتهي كل فترة بعد بدايتها.", "ds.err_overlap": "توجد فترتان متداخلتان في اليوم نفسه.",
    "ds.save": "حفظ الأوقات", "ds.saving": "جارٍ الحفظ…", "ds.saved": "حُفظت أوقاتك.", "ds.discard": "تجاهل التغييرات",
    "ds.no_hours": "لم تحدد أي أوقات بعد.",
    "ds.upcoming": "المواعيد القادمة", "ds.past": "المواعيد السابقة",
    "ds.none": "لا توجد مواعيد محجوزة بعد.",
    "ds.privacy": "لا ترى من حجز: فقط الوقت واللغة والموضوع إن كتبه، والملخص إن وافق السائل على مشاركته.",
    "ds.minutes": "{n} دقيقة",
    "ds.st_booked": "محجوز", "ds.st_done": "تمت", "ds.st_missed_you": "لم تحضر", "ds.st_missed_seeker": "لم يحضر السائل",
    "ds.st_cancel_you": "ألغيته", "ds.st_cancel_seeker": "ألغاه السائل",
    "ds.cancel": "إلغاء", "ds.cancel_title": "إلغاء الموعد",
    "ds.cancel_lead": "سيرى السائل أن الموعد أُلغي، مع رسالتك إن كتبتها، ويمكنه حجز موعد آخر.",
    "ds.cancel_note": "رسالة للسائل", "ds.cancel_ph": "مثلاً: اعتذر لظرف طارئ، أرجو حجز موعد آخر.",
    "ds.cancel_yes": "إلغاء الموعد", "ds.keep": "إبقاء الموعد", "ds.cancelled": "أُلغي الموعد.",
    "ds.soon_title": "مكالمات محجوزة قريبًا",
    "ds.seeker_waiting": "السائل ينتظر", "ds.start": "ابدأ المكالمة", "ds.start_at": "يمكنك البدء الساعة {time}",
    "ds.quiet": "لن تصلك طلبات «اتصل الآن» الجديدة حتى تنتهي من موعدك المحجوز.",
    "ds.st_missed_both": "لم يبدأ", "ds.st_moved": "نقله السائل إلى موعد آخر",
    "ds.booked_call": "مكالمة محجوزة {from} – {to}", "ds.seeker_came": "السائل في المكالمة", "ds.seeker_not_yet": "ننتظر انضمام السائل…",
    "ds.no_show": "السائل لم يحضر", "ds.no_show_done": "سُجّل أن السائل لم يحضر.",
    "ds.today_n": "{n} موعد خلال 24 ساعة", "ds.today_n.one": "موعد واحد خلال 24 ساعة", "ds.today_n.two": "موعدان خلال 24 ساعة",
    "ds.today_n.few": "{n} مواعيد خلال 24 ساعة", "ds.today_n.many": "{n} موعدًا خلال 24 ساعة",
  },
  en: {
    "ds.tab": "My schedule",
    "ds.title": "Hours for booked calls",
    "ds.lead": "Set when seekers can book a call with you. Each range is cut into 30-minute slots, and bookings are confirmed automatically.",
    "ds.taking": "Taking bookings",
    "ds.paused_note": "Bookings are paused: seekers don't see your times. Bookings already made stay as they are.",
    "ds.first_time": "You haven't set your hours yet. Pick the days and times, then save.",
    "ds.tz": "Your time zone", "ds.tz_hint": "You set times in your zone; each seeker sees them in theirs.",
    "ds.slots_note": "Seekers book 30 minutes, or a full hour when the next slot is free too. Bookings close 2 hours before the start and open 14 days ahead.",
    "ds.day_sun": "Sunday", "ds.day_mon": "Monday", "ds.day_tue": "Tuesday", "ds.day_wed": "Wednesday", "ds.day_thu": "Thursday", "ds.day_fri": "Friday", "ds.day_sat": "Saturday",
    "ds.closed": "Unavailable", "ds.from": "From", "ds.to": "To", "ds.remove": "Remove", "ds.add": "Add hours", "ds.copy_all": "Copy to all days",
    "ds.days_off": "Days off", "ds.days_off_hint": "Your times don't show on these days. Bookings already made are never cancelled automatically.", "ds.add_off": "Add day",
    "ds.clash": "You have bookings on your days off ({n}). Cancel them in the list below if you can't make them.",
    "ds.err_order": "Each range must end after it starts.", "ds.err_overlap": "Two ranges overlap on the same day.",
    "ds.save": "Save hours", "ds.saving": "Saving…", "ds.saved": "Your hours are saved.", "ds.discard": "Discard changes",
    "ds.no_hours": "No hours set yet.",
    "ds.upcoming": "Upcoming bookings", "ds.past": "Past bookings",
    "ds.none": "No bookings yet.",
    "ds.privacy": "You don't see who booked: only the time, language, the topic if they wrote one, and the summary if they agreed to share it.",
    "ds.minutes": "{n} minutes",
    "ds.st_booked": "Booked", "ds.st_done": "Completed", "ds.st_missed_you": "You missed it", "ds.st_missed_seeker": "Seeker didn't come",
    "ds.st_cancel_you": "You cancelled", "ds.st_cancel_seeker": "Seeker cancelled",
    "ds.cancel": "Cancel", "ds.cancel_title": "Cancel booking",
    "ds.cancel_lead": "The seeker will see that the booking was cancelled, with your message if you write one, and can book another time.",
    "ds.cancel_note": "Message to the seeker", "ds.cancel_ph": "e.g. Sorry, something urgent came up. Please book another time.",
    "ds.cancel_yes": "Cancel booking", "ds.keep": "Keep booking", "ds.cancelled": "Booking cancelled.",
    "ds.soon_title": "Booked calls coming up",
    "ds.seeker_waiting": "Seeker is waiting", "ds.start": "Start call", "ds.start_at": "You can start at {time}",
    "ds.quiet": "New \"call now\" requests are held back until your booked call is done.",
    "ds.st_missed_both": "Didn't take place", "ds.st_moved": "Seeker moved it to another time",
    "ds.booked_call": "Booked call {from} – {to}", "ds.seeker_came": "The seeker is here", "ds.seeker_not_yet": "Waiting for the seeker to join…",
    "ds.no_show": "Seeker didn't come", "ds.no_show_done": "Marked as a no-show.",
    "ds.today_n": "{n} bookings in the next 24 hours", "ds.today_n.one": "1 booking in the next 24 hours",
  },
});
