// Strings for the da'i console (login, calls tab, groups and meetups tabs). Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "dai.title": "لوحة الداعية", "dai.lead": "للدعاة والمراجعين فقط. استقبل طلبات الاتصال بلغاتك، وقُد مجموعاتك، وانشر لقاءاتك.",
    "dai.user": "اسم المستخدم", "dai.pass": "كلمة المرور", "dai.login": "دخول", "dai.bad": "اسم المستخدم أو كلمة المرور غير صحيحة.",
    "dai.demo": "حسابات تجريبية للتحكيم: khalid و maryam و yusuf و reviewer. كلمة المرور في ملف README.",
    "dai.available": "متاح لاستقبال المكالمات", "dai.logout": "خروج", "dai.langs": "لغاتك: {l}",
    "dc.tab": "الاتصالات",
    "dc.queue": "طلبات الاتصال",
    "dc.queue_empty": "لا توجد طلبات الآن. فعّل حالة «متاح» لتصلك الطلبات بلغاتك.",
    "dc.waiting": "ينتظر منذ {s}",
    "dc.card": "ملخص مرفق",
    "dc.no_card": "بلا ملخص",
    "dc.accept": "قبول",
    "dc.taken": "قبل داعية آخر هذا الطلب.",
    "dc.active": "مكالمتك الحالية",
    "dc.card_title": "ملخص السؤال (بموافقة السائل)",
    "dc.no_card_long": "لم يشارك السائل ملخصاً. اسأله عن سؤاله بلطف.",
    "dc.question": "السؤال",
    "dc.context": "الخلفية",
    "dc.explained": "ما شرحه المساعد",
    "dc.unclear": "ما زال غير واضح",
    "dc.understood": "فهمتُ السؤال",
    "dc.understood_done": "سُجّل وقت الفهم",
    "dc.end": "إنهاء المكالمة",
    "dc.feedback": "قبل أن تنهي",
    "dc.reexplain": "هل احتجت أن يعيد السائل شرح خلفيته؟",
    "dc.accurate": "هل كان الملخص دقيقاً؟",
    "dc.na": "لا ينطبق",
    "dc.note": "ملاحظة (اختياري)",
    "dc.submit": "حفظ وإنهاء",
    "dc.exp": "تجربة ملخص الإحالة",
    "dc.exp_on": "التجربة مفعّلة: تتناوب الطلبات بين ملخص النموذج والقالب الثابت وبلا ملخص.",
    "dc.exp_off": "التجربة متوقفة: يُقترح ملخص النموذج دائماً.",
    "dc.exp_toggle": "تفعيل التجربة",
    "dc.arm.model": "ملخص النموذج",
    "dc.arm.template": "قالب ثابت",
    "dc.arm.none": "بلا ملخص",
    "dc.arm.direct": "اتصال مباشر",
    "dc.calls_one": "مكالمة واحدة", "dc.calls_two": "مكالمتان", "dc.calls_few": "{n} مكالمات", "dc.calls_many": "{n} مكالمة",
    "dc.no_reexplain": "دون إعادة شرح",
    "dc.accuracy": "دقة الملخص",
    "dc.median": "وسيط زمن الفهم",
    "dg.tab": "المجموعات",
    "dm.tab": "الفعاليات",
    "dg.groups": "مجموعاتي",
    "dg.new": "مجموعة جديدة",
    "dg.open": "إدارة",
    "dg.flags": "{n} بانتظار توضيحك",
    "dg.empty": "لا تقود أي مجموعة بعد.",
    "dg.title": "العنوان",
    "dg.desc": "وصف قصير",
    "dg.lang": "اللغة",
    "dg.city": "المدينة",
    "dg.country": "الدولة",
    "dg.audience": "الفئة",
    "dg.create": "إنشاء",
    "dg.post_ph": "اكتب رسالة للمجموعة بصفتك القائد…",
    "dg.delete": "حذف",
    "dg.mute": "إيقاف مشاركة الكاتب",
    "dg.muted_ok": "أُوقفت مشاركة هذا العضو.",
    "dg.resolve": "تم التوضيح",
    "dg.back": "كل مجموعاتي",
    "dm.meetups": "فعالياتي",
    "dm.new": "فعالية جديدة",
    "dm.empty": "لا توجد فعاليات بعد.",
    "dm.attendees": "الحضور ({n})",
    "dm.cancel": "إلغاء الفعالية",
    "dm.cancelled": "ملغى",
    "dm.venue": "المكان (مكان عام)",
    "dm.when": "الموعد",
    "dm.duration": "المدة بالدقائق",
    "dm.capacity": "العدد الأقصى",
    "dm.public": "أؤكد أن المكان عام (مركز، مسجد، مكتبة، قاعة عامة).",
    "dm.create": "نشر الفعالية",
    "dm.group": "ربط بمجموعة (اختياري)",
    "dm.none": "بلا",
    "dm.kind": "طريقة الحضور", "dm.kind_required": "يحجز الحاضر مقعداً باسم مستعار ويحصل على رمز حجز.",
    "dm.kind_required_online": "يحجز الحاضر مقعداً باسم مستعار، ثم يظهر له رابط اللقاء.",
    "dm.kind_open": "لا حجز: يظهر اللقاء للجميع ويحضر من شاء مباشرة.", "dm.capacity_open": "العدد المتوقع",
    "dm.series": "السلسلة (اختياري)", "dm.kids_note": "لقاءات الأطفال يحضرها الطفل مع ولي أمره، ويؤكد ولي الأمر ذلك عند الحجز.",
    "dl.tab": "سجل المكالمات", "dl.title": "مكالماتي في {m}", "dl.month": "الشهر", "dl.calls": "مكالمة رددتُ عليها", "dl.minutes": "دقيقة حوار",
    "dl.no_reexplain": "إحالة دون إعادة شرح", "dl.of": "{a} من {b}", "dl.rating": "متوسط تقييم السائلين",
    "dl.privacy": "يُحفظ هنا ما تحتاجه التجربة من أرقام فقط. لا يُسجَّل صوت المكالمة، ولا يظهر ما يدل على هوية السائل. ولا تظهر محادثة السائل مع سَبِيلي إلا إذا اختار مشاركتها معك.",
    "dl.empty": "لا توجد مكالمات رددتَ عليها في هذا الشهر.", "dl.when": "التاريخ والوقت", "dl.lang": "اللغة", "dl.length": "المدة",
    "dl.arm": "نوع الإحالة", "dl.understood": "فهمت السؤال بعد", "dl.reexplain": "أعاد الشرح؟", "dl.accurate": "الملخص دقيق؟",
    "dl.stars": "التقييم", "dl.note": "ملاحظتي",
    "dl.chat": "المحادثة المشتركة", "dl.chat_show": "اعرضها", "dl.chat_gone": "حذف السائل هذه المحادثة، فلم تعد متاحة.",
    "dp.tab": "ملفي", "dp.edit": "بياناتي", "dp.titled_m": "الداعية {n}", "dp.titled_f": "الداعية {n}",
    "dp.name": "الاسم بالعربية", "dp.name_en": "الاسم بالإنجليزية", "dp.langs": "لغاتي",
    "dp.langs_hint": "يصلك طلب الاتصال فقط من سائل يختار إحدى لغاتك.", "dp.one_lang": "اختر لغة واحدة على الأقل.",
    "dp.bio": "نبذة بالعربية", "dp.bio_en": "نبذة بالإنجليزية", "dp.count": "{n} من 600",
    "dp.save": "حفظ", "dp.saving": "جارٍ الحفظ…", "dp.saved": "حُفظ ملفك.", "dp.reset": "تراجع",
    "dp.invalid": "تأكد من الاسم ومن اختيار لغة واحدة على الأقل.", "dp.preview": "هكذا يراك السائل", "dp.no_bio": "لا توجد نبذة بعد.",
    "dp.gender": "أنا", "dp.gender_m": "داعية (رجل)", "dp.gender_f": "داعية (امرأة)", "dp.country": "الدولة", "dp.city": "المدينة",
    "dc.for_you": "طلبك بالاسم",
    "dc.chat_badge": "شارك محادثته", "dc.chat_title": "محادثة السائل مع سَبِيلي", "dc.chat_count": "(الأسئلة: {n})",
    "dc.chat_hint": "شاركها السائل بموافقته كما كانت عند طلب الاتصال. الإجابات من المصادر المعتمدة كما رآها.",
    "dc.seeker_asked": "سأل:", "dc.photo": "أرفق صورة", "dc.chat_show": "اعرض المحادثة كاملة",
    "dai.disabled": "هذا الحساب موقوف. تواصل مع المراجع.", "dai.too_many": "محاولات كثيرة. انتظر عشر دقائق ثم حاول.",
    "da.tab": "حسابات الدعاة", "da.langs": "لغاته", "da.gender": "الداعية", "da.add": "أضف داعية", "da.do_add": "أضف الحساب", "da.added": "أُضيف الحساب {u}.",
    "da.user_hint": "حروف إنجليزية صغيرة وأرقام و _ أو . (٣ إلى ٣٢).", "da.first_password": "كلمة مرور أولى",
    "da.pass_hint": "٨ أحرف على الأقل. أرسلها للداعية بطريقة آمنة.",
    "da.list": "الدعاة والمراجعون", "da.list_lead": "الحساب الموقوف لا يستطيع الدخول ولا يظهر للسائلين. تغيير كلمة المرور يُخرج الداعية من كل أجهزته.",
    "da.reviewer": "مراجع", "da.disabled": "موقوف", "da.disable": "أوقف", "da.enable": "فعّل",
    "da.disabled_done": "أُوقف الحساب.", "da.enabled_done": "فُعّل الحساب.",
    "da.reset": "كلمة مرور جديدة", "da.new_password": "كلمة المرور الجديدة", "da.reset_done": "تغيّرت كلمة المرور.",
    "da.invalid": "تأكد من اسم المستخدم والاسم وكلمة المرور (٨ أحرف على الأقل).",
    "da.err.username taken": "اسم المستخدم مأخوذ.", "da.err.you can't disable your own account": "لا يمكنك إيقاف حسابك.",
  },
  en: {
    "dai.title": "Da'i console", "dai.lead": "For da'is and reviewers only. Take call requests in your languages, lead your groups and publish meetups.",
    "dai.user": "Username", "dai.pass": "Password", "dai.login": "Sign in", "dai.bad": "Wrong username or password.",
    "dai.demo": "Demo accounts for judging: khalid, maryam, yusuf and reviewer. The password is in the README.",
    "dai.available": "Available for calls", "dai.logout": "Sign out", "dai.langs": "Your languages: {l}",
    "dc.tab": "Calls",
    "dc.queue": "Call requests",
    "dc.queue_empty": "No requests right now. Switch to Available to receive requests in your languages.",
    "dc.waiting": "waiting {s}",
    "dc.card": "Summary attached",
    "dc.no_card": "No summary",
    "dc.accept": "Accept",
    "dc.taken": "Another da'i took this request.",
    "dc.active": "Your current call",
    "dc.card_title": "Question summary (shared by the seeker)",
    "dc.no_card_long": "The seeker didn't share a summary. Kindly ask about their question.",
    "dc.question": "Question",
    "dc.context": "Background",
    "dc.explained": "What the assistant explained",
    "dc.unclear": "Still unclear",
    "dc.understood": "I understand the question",
    "dc.understood_done": "Time to understand recorded",
    "dc.end": "End call",
    "dc.feedback": "Before you finish",
    "dc.reexplain": "Did the seeker have to re-explain their background?",
    "dc.accurate": "Was the summary accurate?",
    "dc.na": "N/A",
    "dc.note": "Note (optional)",
    "dc.submit": "Save and finish",
    "dc.exp": "Referral summary experiment",
    "dc.exp_on": "Experiment on: requests rotate between the AI summary, a fixed template and no summary.",
    "dc.exp_off": "Experiment off: the AI summary is always suggested.",
    "dc.exp_toggle": "Run the experiment",
    "dc.arm.model": "AI summary",
    "dc.arm.template": "Fixed template",
    "dc.arm.none": "No summary",
    "dc.arm.direct": "Direct call",
    "dc.calls_one": "1 call", "dc.calls_two": "2 calls", "dc.calls_few": "{n} calls", "dc.calls_many": "{n} calls",
    "dc.no_reexplain": "no re-explaining",
    "dc.accuracy": "summary accurate",
    "dc.median": "median time to understand",
    "dg.tab": "Groups",
    "dm.tab": "Events",
    "dg.groups": "My groups",
    "dg.new": "New group",
    "dg.open": "Manage",
    "dg.flags": "{n} waiting for you",
    "dg.empty": "You don't lead any group yet.",
    "dg.title": "Title",
    "dg.desc": "Short description",
    "dg.lang": "Language",
    "dg.city": "City",
    "dg.country": "Country",
    "dg.audience": "Audience",
    "dg.create": "Create",
    "dg.post_ph": "Write to the group as its leader…",
    "dg.delete": "Delete",
    "dg.mute": "Pause the author",
    "dg.muted_ok": "This member is paused.",
    "dg.resolve": "Clarified",
    "dg.back": "All my groups",
    "dm.meetups": "My events",
    "dm.new": "New event",
    "dm.empty": "No events yet.",
    "dm.attendees": "Attending ({n})",
    "dm.cancel": "Cancel event",
    "dm.cancelled": "Cancelled",
    "dm.venue": "Venue (a public place)",
    "dm.when": "Date and time",
    "dm.duration": "Duration (minutes)",
    "dm.capacity": "Capacity",
    "dm.public": "I confirm the venue is public (a centre, mosque, library or public hall).",
    "dm.create": "Publish event",
    "dm.group": "Link to a group (optional)",
    "dm.none": "None",
    "dm.kind": "How people attend", "dm.kind_required": "Attendees reserve a spot with a nickname and get a booking code.",
    "dm.kind_required_online": "Attendees reserve a spot with a nickname, then see the meeting link.",
    "dm.kind_open": "No booking: the meetup is listed and anyone can just come.", "dm.capacity_open": "Expected attendance",
    "dm.series": "Series (optional)", "dm.kids_note": "Children attend with a guardian, who confirms it when booking.",
    "dl.tab": "Call log", "dl.title": "My calls in {m}", "dl.month": "Month", "dl.calls": "calls answered", "dl.minutes": "minutes of conversation",
    "dl.no_reexplain": "referrals with no re-explaining", "dl.of": "{a} of {b}", "dl.rating": "average seeker rating",
    "dl.privacy": "Only the numbers the experiment needs are kept. Call audio is never recorded, and nothing identifies the seeker. A seeker's chat with Sabeeli shows only if they chose to share it with you.",
    "dl.empty": "You didn't answer any calls this month.", "dl.when": "Date and time", "dl.lang": "Language", "dl.length": "Length",
    "dl.arm": "Referral type", "dl.understood": "Understood after", "dl.reexplain": "Re-explained?", "dl.accurate": "Summary accurate?",
    "dl.stars": "Rating", "dl.note": "My note",
    "dl.chat": "Shared chat", "dl.chat_show": "Show", "dl.chat_gone": "The seeker deleted this chat, so it's no longer available.",
    "dp.tab": "My profile", "dp.edit": "My details", "dp.titled_m": "Da'i {n}", "dp.titled_f": "Da'iyah {n}",
    "dp.name": "Name in Arabic", "dp.name_en": "Name in English", "dp.langs": "My languages",
    "dp.langs_hint": "You only receive call requests from seekers who choose one of your languages.", "dp.one_lang": "Choose at least one language.",
    "dp.bio": "Bio in Arabic", "dp.bio_en": "Bio in English", "dp.count": "{n} of 600",
    "dp.save": "Save", "dp.saving": "Saving…", "dp.saved": "Your profile is saved.", "dp.reset": "Undo",
    "dp.invalid": "Check your name and choose at least one language.", "dp.preview": "How seekers see you", "dp.no_bio": "No bio yet.",
    "dp.gender": "I am", "dp.gender_m": "Male da'i", "dp.gender_f": "Female da'iyah", "dp.country": "Country", "dp.city": "City",
    "dc.for_you": "Asked for you",
    "dc.chat_badge": "Chat shared", "dc.chat_title": "The seeker's chat with Sabeeli", "dc.chat_count": "({n} questions)",
    "dc.chat_hint": "Shared by the seeker with their OK, as it was when they asked for the call. The answers are from the approved sources, as they saw them.",
    "dc.seeker_asked": "They asked:", "dc.photo": "Attached a photo", "dc.chat_show": "Show the whole conversation",
    "dai.disabled": "This account is disabled. Contact the reviewer.", "dai.too_many": "Too many attempts. Wait ten minutes and try again.",
    "da.tab": "Da'i accounts", "da.langs": "Languages", "da.gender": "Da'i", "da.add": "Add a da'i", "da.do_add": "Add account", "da.added": "Account {u} added.",
    "da.user_hint": "Lower-case letters, digits, _ or . (3 to 32).", "da.first_password": "First password",
    "da.pass_hint": "At least 8 characters. Send it to the da'i safely.",
    "da.list": "Da'is and reviewers", "da.list_lead": "A disabled account can't sign in and isn't shown to seekers. A new password signs the da'i out on every device.",
    "da.reviewer": "Reviewer", "da.disabled": "Disabled", "da.disable": "Disable", "da.enable": "Enable",
    "da.disabled_done": "Account disabled.", "da.enabled_done": "Account enabled.",
    "da.reset": "New password", "da.new_password": "New password", "da.reset_done": "Password changed.",
    "da.invalid": "Check the username, the name and the password (at least 8 characters).",
    "da.err.username taken": "That username is taken.", "da.err.you can't disable your own account": "You can't disable your own account.",
  },
});
