// Strings for the da'i console (login, calls tab, groups and meetups tabs). Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "dai.title": "لوحة الداعية", "dai.lead": "للدعاة والمراجعين فقط. استقبل طلبات الاتصال بلغاتك، وقُد مجموعاتك، وانشر لقاءاتك.",
    "dai.user": "اسم المستخدم", "dai.pass": "كلمة المرور", "dai.login": "دخول", "dai.bad": "اسم المستخدم أو كلمة المرور غير صحيحة.",
    "dai.demo": "حسابات تجريبية للتحكيم: khalid و maryam و yusuf و reviewer. كلمة المرور في ملف README.",
    "dai.available": "متاح لاستقبال المكالمات", "dai.logout": "خروج", "dai.langs": "لغاتك: {l}",
    "dc.tab": "الاتصالات",
    "dc.queue": "طلبات الاتصال",
    "dc.queue_empty": "لا توجد طلبات الآن. فعّل حالة «متاح» لتصلك الطلبات بلغاتك.",
    "dc.waiting": "ينتظر منذ {s}",
    "dc.card": "ملخص مرفق",
    "dc.no_card": "بلا ملخص",
    "dc.accept": "قبول",
    "dc.taken": "قبل داعية آخر هذا الطلب.",
    "dc.active": "مكالمتك الحالية",
    "dc.card_title": "ملخص السؤال (بموافقة السائل)",
    "dc.no_card_long": "لم يشارك السائل ملخصاً. اسأله عن سؤاله بلطف.",
    "dc.question": "السؤال",
    "dc.context": "الخلفية",
    "dc.explained": "ما شرحه المساعد",
    "dc.unclear": "ما زال غير واضح",
    "dc.understood": "فهمتُ السؤال",
    "dc.understood_done": "سُجّل وقت الفهم",
    "dc.end": "إنهاء المكالمة",
    "dc.feedback": "قبل أن تنهي",
    "dc.reexplain": "هل احتجت أن يعيد السائل شرح خلفيته؟",
    "dc.accurate": "هل كان الملخص دقيقاً؟",
    "dc.na": "لا ينطبق",
    "dc.note": "ملاحظة (اختياري)",
    "dc.submit": "حفظ وإنهاء",
    "dc.exp": "تجربة ملخص الإحالة",
    "dc.exp_on": "التجربة مفعّلة: تتناوب الطلبات بين ملخص النموذج والقالب الثابت وبلا ملخص.",
    "dc.exp_off": "التجربة متوقفة: يُقترح ملخص النموذج دائماً.",
    "dc.exp_toggle": "تفعيل التجربة",
    "dc.arm.model": "ملخص النموذج",
    "dc.arm.template": "قالب ثابت",
    "dc.arm.none": "بلا ملخص",
    "dc.arm.direct": "اتصال مباشر",
    "dc.calls": "مكالمات",
    "dc.no_reexplain": "دون إعادة شرح",
    "dc.accuracy": "دقة الملخص",
    "dc.median": "وسيط زمن الفهم",
    "dg.tab": "المجموعات",
    "dm.tab": "اللقاءات",
    "dg.groups": "مجموعاتي",
    "dg.new": "مجموعة جديدة",
    "dg.open": "إدارة",
    "dg.flags": "{n} بانتظار توضيحك",
    "dg.empty": "لا تقود أي مجموعة بعد.",
    "dg.title": "العنوان",
    "dg.desc": "وصف قصير",
    "dg.lang": "اللغة",
    "dg.city": "المدينة",
    "dg.country": "رمز الدولة (مثل SA)",
    "dg.audience": "الفئة",
    "dg.create": "إنشاء",
    "dg.post_ph": "اكتب رسالة للمجموعة بصفتك القائد…",
    "dg.delete": "حذف",
    "dg.mute": "إيقاف مشاركة الكاتب",
    "dg.muted_ok": "أُوقفت مشاركة هذا العضو.",
    "dg.resolve": "تم التوضيح",
    "dg.back": "كل مجموعاتي",
    "dm.meetups": "لقاءاتي",
    "dm.new": "لقاء جديد",
    "dm.empty": "لا توجد لقاءات بعد.",
    "dm.attendees": "الحضور ({n})",
    "dm.cancel": "إلغاء اللقاء",
    "dm.cancelled": "ملغى",
    "dm.venue": "المكان (مكان عام)",
    "dm.when": "الموعد",
    "dm.duration": "المدة بالدقائق",
    "dm.capacity": "العدد الأقصى",
    "dm.public": "أؤكد أن المكان عام (مركز، مسجد، مكتبة، قاعة عامة).",
    "dm.create": "نشر اللقاء",
    "dm.group": "ربط بمجموعة (اختياري)",
    "dm.none": "بلا",
  },
  en: {
    "dai.title": "Da'i console", "dai.lead": "For da'is and reviewers only. Take call requests in your languages, lead your groups and publish meetups.",
    "dai.user": "Username", "dai.pass": "Password", "dai.login": "Sign in", "dai.bad": "Wrong username or password.",
    "dai.demo": "Demo accounts for judging: khalid, maryam, yusuf and reviewer. The password is in the README.",
    "dai.available": "Available for calls", "dai.logout": "Sign out", "dai.langs": "Your languages: {l}",
    "dc.tab": "Calls",
    "dc.queue": "Call requests",
    "dc.queue_empty": "No requests right now. Switch to Available to receive requests in your languages.",
    "dc.waiting": "waiting {s}",
    "dc.card": "Summary attached",
    "dc.no_card": "No summary",
    "dc.accept": "Accept",
    "dc.taken": "Another da'i took this request.",
    "dc.active": "Your current call",
    "dc.card_title": "Question summary (shared by the seeker)",
    "dc.no_card_long": "The seeker didn't share a summary. Kindly ask about their question.",
    "dc.question": "Question",
    "dc.context": "Background",
    "dc.explained": "What the assistant explained",
    "dc.unclear": "Still unclear",
    "dc.understood": "I understand the question",
    "dc.understood_done": "Time to understand recorded",
    "dc.end": "End call",
    "dc.feedback": "Before you finish",
    "dc.reexplain": "Did the seeker have to re-explain their background?",
    "dc.accurate": "Was the summary accurate?",
    "dc.na": "N/A",
    "dc.note": "Note (optional)",
    "dc.submit": "Save and finish",
    "dc.exp": "Referral summary experiment",
    "dc.exp_on": "Experiment on: requests rotate between the AI summary, a fixed template and no summary.",
    "dc.exp_off": "Experiment off: the AI summary is always suggested.",
    "dc.exp_toggle": "Run the experiment",
    "dc.arm.model": "AI summary",
    "dc.arm.template": "Fixed template",
    "dc.arm.none": "No summary",
    "dc.arm.direct": "Direct call",
    "dc.calls": "calls",
    "dc.no_reexplain": "no re-explaining",
    "dc.accuracy": "summary accurate",
    "dc.median": "median time to understand",
    "dg.tab": "Groups",
    "dm.tab": "Meetups",
    "dg.groups": "My groups",
    "dg.new": "New group",
    "dg.open": "Manage",
    "dg.flags": "{n} waiting for you",
    "dg.empty": "You don't lead any group yet.",
    "dg.title": "Title",
    "dg.desc": "Short description",
    "dg.lang": "Language",
    "dg.city": "City",
    "dg.country": "Country code (e.g. GB)",
    "dg.audience": "Audience",
    "dg.create": "Create",
    "dg.post_ph": "Write to the group as its leader…",
    "dg.delete": "Delete",
    "dg.mute": "Pause the author",
    "dg.muted_ok": "This member is paused.",
    "dg.resolve": "Clarified",
    "dg.back": "All my groups",
    "dm.meetups": "My meetups",
    "dm.new": "New meetup",
    "dm.empty": "No meetups yet.",
    "dm.attendees": "Attending ({n})",
    "dm.cancel": "Cancel meetup",
    "dm.cancelled": "Cancelled",
    "dm.venue": "Venue (a public place)",
    "dm.when": "Date and time",
    "dm.duration": "Duration (minutes)",
    "dm.capacity": "Capacity",
    "dm.public": "I confirm the venue is public (a centre, mosque, library or public hall).",
    "dm.create": "Publish meetup",
    "dm.group": "Link to a group (optional)",
    "dm.none": "None",
  },
});
