// Account strings. Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "acc.email_optional": "البريد الإلكتروني (اختياري)", "acc.email_title": "البريد لاستعادة الحساب",
    "acc.email_hint": "لا يظهر لأحد. نحفظه فقط لنرسل لك رمزاً إن نسيت كلمة المرور، حين يكون الإرسال بالبريد مفعّلاً في الموقع. وتستطيع دائماً إنشاء رمز استعادة من قسم الأمان في حسابك.",
    "acc.err.email taken": "هذا البريد مرتبط بحساب آخر.",
    "acc.mine": "حسابي", "acc.signin_btn": "تسجيل الدخول",
    "acc.signin_title": "تسجيل الدخول", "acc.signin_lead": "ادخل لتحفظ محادثاتك وحجوزاتك على كل أجهزتك.",
    "acc.signup_title": "إنشاء حساب", "acc.signup_lead": "الحساب اختياري، ويحفظ محادثاتك وحجوزاتك ومجموعاتك.",
    "acc.no_account": "ليس لديك حساب؟", "acc.have_account": "لديك حساب؟", "acc.create_account": "أنشئ حساباً",
    "acc.role_label": "تسجيل الدخول بصفة", "acc.role_user": "مستخدم", "acc.role_daai": "داعية", "acc.daai_console": "لوحة الداعية",
    "acc.daai_lead": "للدعاة والمراجعين: استقبل طلبات الاتصال، وأدر مجموعاتك وفعالياتك.",
    "acc.daai_note": "حسابات الدعاة يضيفها المراجع.",
    "acc.sample_title": "حسابات للتجربة:", "acc.sample_daai": "اضغط اسماً لتعبئته، وكلمة المرور لكلها {p}.",
    "acc.sample_reviewer": "مراجع", "acc.sample_user": "لا توجد حسابات مستخدمين جاهزة للتجربة: أنشئ حسابك المجاني خلال دقيقة.",
    "acc.err.daai_bad": "اسم المستخدم أو كلمة المرور غير صحيحة.", "acc.err.daai_disabled": "هذا الحساب موقوف. تواصل مع المراجع.",
    "acc.err.daai_too_many": "محاولات كثيرة. انتظر عشر دقائق ثم حاول.",
    "acc.username": "اسم المستخدم", "acc.username_hint": "من ٣ إلى ٢٤ حرفاً أو رقماً، ويظهر للآخرين في المجموعات. لا تستخدم اسمك الحقيقي.",
    "acc.password": "كلمة المرور", "acc.password_hint": "٨ أحرف على الأقل.", "acc.new_password": "كلمة المرور الجديدة",
    "acc.do_signin": "تسجيل الدخول", "acc.do_signup": "أنشئ الحساب",
    "acc.keep_note": "ما فعلته على هذا الجهاز قبل التسجيل يُحفظ في حسابك.",
    "acc.welcome": "أهلاً {u}", "acc.since": "معك منذ {d}",
    "acc.place": "مكاني", "acc.place_lead": "نعرض لك المجموعات والفعاليات القريبة منك أولاً.", "acc.country": "الدولة",
    "acc.city": "المدينة", "acc.any": "—", "acc.save": "حفظ", "acc.saved": "حُفظ.",
    "acc.about": "عنّي", "acc.about_lead": "اختر جنسك وفئتك العمرية لنقترح عليك المجموعات والفعاليات المناسبة. لا تظهر لأحد، والعمر فئة فقط لا تاريخ ميلاد. الدولة والمدينة اختياريتان.",
    "acc.choose": "اختر…", "acc.no_country": "اختر الدولة (اختياري)",
    "acc.complete_title": "أكمل بياناتك", "acc.complete_lead": "اختر جنسك وفئتك العمرية لنقترح عليك المجموعات والفعاليات المناسبة لك. لا تظهر لأحد.",
    "acc.lang": "اللغة", "acc.gender": "الجنس", "acc.gender_m": "ذكر", "acc.gender_f": "أنثى",
    "acc.age": "العمر", "acc.age.u18": "أقل من ١٨", "acc.age.18_24": "١٨ إلى ٢٤", "acc.age.25_34": "٢٥ إلى ٣٤",
    "acc.age.35_44": "٣٥ إلى ٤٤", "acc.age.45_54": "٤٥ إلى ٥٤", "acc.age.55p": "٥٥ فأكثر",
    "acc.age_minor": "إن كان عمرك أقل من ١٨ فاستأذن وليّ أمرك قبل الاتصال بداعية أو حضور فعالية.",
    "acc.chats": "محادثاتي مع المساعد", "acc.chats_lead": "المحادثات المحفوظة في حسابك: {n}. تراها على أي جهاز تدخل منه، وتحذف أيّاً منها من صفحة اسأل.",
    "acc.chats_none": "لا محادثات محفوظة بعد. ما تسأله وأنت داخل حسابك يُحفظ هنا.", "acc.chats_open": "افتح محادثاتي",
    "acc.chats_delete": "احذف كل المحادثات", "acc.chats_confirm": "نعم، احذفها من كل الأجهزة", "acc.chats_deleted": "حُذفت محادثاتك.",
    "acc.activity": "نشاطي", "acc.my_events": "فعالياتي", "acc.my_groups": "مجموعاتي",
    "acc.no_events": "لم تسجّل أو تنضم إلى فعالية بعد.", "acc.no_groups": "لم تنضم إلى مجموعة بعد.", "acc.browse": "تصفّح المجتمع",
    "acc.security": "الأمان", "acc.current_password": "كلمة المرور الحالية", "acc.change_password": "غيّر كلمة المرور",
    "acc.password_changed": "تغيّرت كلمة المرور، وخرجت من حسابك على أجهزتك الأخرى.", "acc.signout": "تسجيل الخروج", "acc.menu_activities": "أنشطتي", "acc.menu_bookings": "مواعيدي مع الدعاة", "acc.menu_chats": "محادثاتي", "acc.signed_out": "خرجت من حسابك على هذا الجهاز.",
    "acc.delete": "حذف الحساب", "acc.delete_lead": "يحذف الحساب وكل ما فيه من أسئلة وحجوزات ومكالمات على كل الأجهزة، ولا يمكن التراجع.",
    "acc.delete_confirm": "اكتب كلمة المرور لتأكيد الحذف", "acc.do_delete": "احذف نهائياً", "acc.deleted": "حُذف حسابك.",
    "acc.err.username taken": "اسم المستخدم مأخوذ، جرّب غيره.",
    "acc.err.wrong username or password": "اسم المستخدم أو كلمة المرور غير صحيحة.",
    "acc.err.wrong password": "كلمة المرور غير صحيحة.", "acc.err.too many attempts": "محاولات كثيرة. انتظر عشر دقائق ثم حاول.",
    "acc.err.invalid": "تأكد من اسم المستخدم (٣ إلى ٢٤ حرفاً أو رقماً) وكلمة المرور (٨ أحرف على الأقل).",
    // Show/hide password, busy labels, "forgot password?" and recovery codes
    "acc.pw_show": "إظهار كلمة المرور", "acc.pw_hide": "إخفاء كلمة المرور",
    "acc.signing_in": "جارٍ تسجيل الدخول…", "acc.signing_up": "جارٍ إنشاء الحساب…", "acc.changing_password": "جارٍ التغيير…",
    "acc.deleting": "جارٍ الحذف…", "acc.signing_out": "جارٍ الخروج…", "acc.working": "لحظة…",
    "acc.forgot": "نسيت كلمة المرور؟", "acc.fp_title": "استعادة كلمة المرور", "acc.fp_back": "العودة إلى تسجيل الدخول",
    "acc.fp_lead": "اكتب اسم المستخدم أو البريد المرتبط بحسابك.", "acc.fp_login": "اسم المستخدم أو البريد",
    "acc.fp_continue": "متابعة", "acc.fp_have_code": "لدي رمز استعادة",
    "acc.fp_email_sent": "إن كان لهذا الحساب بريد فقد أرسلنا إليه رمزاً من ٦ أرقام، وينتهي خلال ١٥ دقيقة.",
    "acc.fp_email_code": "الرمز الذي وصلك بالبريد", "acc.fp_reset": "غيّر كلمة المرور", "acc.fp_use_code": "استخدم رمز الاستعادة بدلاً من ذلك",
    "acc.fp_email_off": "الاستعادة بالبريد غير متاحة الآن، فاستخدم رمز الاستعادة.",
    "acc.fp_code_lead": "اكتب اسم المستخدم ورمز الاستعادة الذي أنشأته من صفحة حسابك، ثم كلمة مرور جديدة.",
    "acc.fp_recovery_code": "رمز الاستعادة",
    "acc.fp_none": "ليس لديك رمز استعادة ولا بريد في الحساب؟ عندها لا يمكن استعادة كلمة المرور، لأننا لا نحفظ شيئاً آخر يثبت أن الحساب لك، ولا يستطيع الدعاة ولا المراجع إعادة تعيينها. يمكنك إنشاء حساب جديد.",
    "acc.fp_done": "تغيّرت كلمة المرور ودخلت إلى حسابك. رمز الاستعادة القديم لم يعد يعمل، وهذا رمزك الجديد:",
    "acc.err.wrong or expired code": "الرمز غير صحيح أو انتهت مدته.",
    "acc.err.wrong username or recovery code": "اسم المستخدم أو رمز الاستعادة غير صحيح.",
    "acc.rc_title": "رمز الاستعادة", "acc.rc_lead": "إن نسيت كلمة المرور فهذا الرمز يعيدك إلى حسابك. إنشاء رمز جديد يُبطل أي رمز سابق.",
    "acc.rc_create": "أنشئ رمز استعادة", "acc.rc_your_code": "رمز الاستعادة الخاص بك",
    "acc.rc_keep": "احفظه في مكان آمن. لن نعرضه مرة أخرى، ويصلح لمرة واحدة.",
    "acc.rc_copy": "نسخ", "acc.rc_copied": "نُسخ الرمز.", "acc.rc_copy_failed": "تعذّر النسخ. انسخ الرمز يدوياً.",
  },
  en: {
    "acc.email_optional": "Email (optional)", "acc.email_title": "Email for account recovery",
    "acc.email_hint": "Nobody else sees it. We keep it only to send you a code if you forget your password, when this site has email sending turned on. You can always create a recovery code under Security in your account.",
    "acc.err.email taken": "That email is linked to another account.",
    "acc.mine": "My account", "acc.signin_btn": "Sign in",
    "acc.signin_title": "Sign in", "acc.signin_lead": "Sign in to keep your chats and bookings on all your devices.",
    "acc.signup_title": "Create an account", "acc.signup_lead": "An account is optional. It keeps your chats, bookings and groups.",
    "acc.no_account": "Don't have an account?", "acc.have_account": "Already have an account?", "acc.create_account": "Create one",
    "acc.role_label": "Sign in as", "acc.role_user": "User", "acc.role_daai": "Da'i", "acc.daai_console": "Da'i console",
    "acc.daai_lead": "For da'is and reviewers: take call requests and run your groups and events.",
    "acc.daai_note": "Da'i accounts are added by the reviewer.",
    "acc.sample_title": "Sample accounts to try:", "acc.sample_daai": "Tap a name to fill it in. The password for all of them is {p}.",
    "acc.sample_reviewer": "admin", "acc.sample_user": "There are no ready-made user accounts to try: create your own free account in a minute.",
    "acc.err.daai_bad": "Wrong username or password.", "acc.err.daai_disabled": "This account is disabled. Contact the reviewer.",
    "acc.err.daai_too_many": "Too many attempts. Wait ten minutes and try again.",
    "acc.username": "Username", "acc.username_hint": "3 to 24 letters or digits. Others see it in groups, so don't use your real name.",
    "acc.password": "Password", "acc.password_hint": "At least 8 characters.", "acc.new_password": "New password",
    "acc.do_signin": "Sign in", "acc.do_signup": "Create account",
    "acc.keep_note": "What you did on this device before signing up is kept in your account.",
    "acc.welcome": "Welcome, {u}", "acc.since": "With us since {d}",
    "acc.place": "Where I am", "acc.place_lead": "Groups and events near you are shown first.", "acc.country": "Country",
    "acc.city": "City", "acc.any": "—", "acc.save": "Save", "acc.saved": "Saved.",
    "acc.about": "About me", "acc.about_lead": "Pick your sex and age band so we can suggest groups and events that fit you. Nobody else sees them, and age is a band, never a birth date. Country and city are optional.",
    "acc.choose": "Choose…", "acc.no_country": "Choose a country (optional)",
    "acc.complete_title": "Complete your profile", "acc.complete_lead": "Pick your sex and age band so we can suggest groups and events that fit you. Nobody else sees them.",
    "acc.lang": "Language", "acc.gender": "Sex", "acc.gender_m": "Male", "acc.gender_f": "Female",
    "acc.age": "Age", "acc.age.u18": "Under 18", "acc.age.18_24": "18 to 24", "acc.age.25_34": "25 to 34",
    "acc.age.35_44": "35 to 44", "acc.age.45_54": "45 to 54", "acc.age.55p": "55 or over",
    "acc.age_minor": "If you're under 18, ask a parent or guardian before calling a da'i or going to an event.",
    "acc.chats": "My chats with the assistant", "acc.chats_lead": "Chats saved to your account: {n}. You see them on any device you sign in on, and can delete any one of them on the Ask page.",
    "acc.chats_none": "No saved chats yet. What you ask while signed in is saved here.", "acc.chats_open": "Open my chats",
    "acc.chats_delete": "Delete all chats", "acc.chats_confirm": "Yes, delete them on every device", "acc.chats_deleted": "Your chats were deleted.",
    "acc.activity": "My activity", "acc.my_events": "My events", "acc.my_groups": "My groups",
    "acc.no_events": "You haven't registered for or joined an event yet.", "acc.no_groups": "You haven't joined a group yet.", "acc.browse": "Browse the community",
    "acc.security": "Security", "acc.current_password": "Current password", "acc.change_password": "Change password",
    "acc.password_changed": "Password changed. You were signed out on your other devices.", "acc.signout": "Sign out", "acc.menu_activities": "My activities", "acc.menu_bookings": "My bookings with da'is", "acc.menu_chats": "My chats", "acc.signed_out": "Signed out on this device.",
    "acc.delete": "Delete account", "acc.delete_lead": "Deletes the account and all its questions, bookings and calls on every device. This can't be undone.",
    "acc.delete_confirm": "Type your password to confirm", "acc.do_delete": "Delete for good", "acc.deleted": "Your account was deleted.",
    "acc.err.username taken": "That username is taken. Try another.",
    "acc.err.wrong username or password": "Wrong username or password.",
    "acc.err.wrong password": "Wrong password.", "acc.err.too many attempts": "Too many attempts. Wait ten minutes and try again.",
    "acc.err.invalid": "Check the username (3 to 24 letters or digits) and the password (at least 8 characters).",
    // Show/hide password, busy labels, "forgot password?" and recovery codes
    "acc.pw_show": "Show password", "acc.pw_hide": "Hide password",
    "acc.signing_in": "Signing in…", "acc.signing_up": "Creating account…", "acc.changing_password": "Changing…",
    "acc.deleting": "Deleting…", "acc.signing_out": "Signing out…", "acc.working": "One moment…",
    "acc.forgot": "Forgot password?", "acc.fp_title": "Reset your password", "acc.fp_back": "Back to sign in",
    "acc.fp_lead": "Enter your username or the email on your account.", "acc.fp_login": "Username or email",
    "acc.fp_continue": "Continue", "acc.fp_have_code": "I have a recovery code",
    "acc.fp_email_sent": "If this account has an email, we sent it a 6-digit code. It expires in 15 minutes.",
    "acc.fp_email_code": "Code from the email", "acc.fp_reset": "Change password", "acc.fp_use_code": "Use a recovery code instead",
    "acc.fp_email_off": "Reset by email isn't available right now, so use your recovery code.",
    "acc.fp_code_lead": "Enter your username, the recovery code you made on your account page, and a new password.",
    "acc.fp_recovery_code": "Recovery code",
    "acc.fp_none": "No recovery code and no email on the account? Then the password can't be reset: we keep nothing else that shows the account is yours, and da'is and the reviewer can't reset it either. You can create a new account.",
    "acc.fp_done": "Your password changed and you're signed in. Your old recovery code no longer works. Here is your new one:",
    "acc.err.wrong or expired code": "That code is wrong or has expired.",
    "acc.err.wrong username or recovery code": "Wrong username or recovery code.",
    "acc.rc_title": "Recovery code", "acc.rc_lead": "If you forget your password, this code gets you back in. Making a new code cancels any earlier one.",
    "acc.rc_create": "Create a recovery code", "acc.rc_your_code": "Your recovery code",
    "acc.rc_keep": "Keep it somewhere safe. We won't show it again, and it works once.",
    "acc.rc_copy": "Copy", "acc.rc_copied": "Code copied.", "acc.rc_copy_failed": "Couldn't copy. Copy the code by hand.",
  },
});
