// Account strings. Owner: Eman.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "acc.email_optional": "البريد الإلكتروني (اختياري)", "acc.email_title": "البريد لاستعادة الحساب",
    "acc.email_hint": "نستخدمه فقط لإرسال رمز إن نسيت كلمة المرور، ولا يظهر لأحد. بدونه لا يمكن استعادة الحساب.",
    "acc.err.email taken": "هذا البريد مرتبط بحساب آخر.", "acc.err.wrong or expired code": "الرمز غير صحيح أو انتهت صلاحيته.",
    "acc.signin": "دخول", "acc.signup": "حساب جديد", "acc.mine": "حسابي", "acc.signin_btn": "تسجيل الدخول",
    "acc.signin_title": "تسجيل الدخول", "acc.signin_lead": "ادخل لتحفظ محادثاتك وحجوزاتك على كل أجهزتك.",
    "acc.signup_title": "إنشاء حساب", "acc.signup_lead": "الحساب اختياري، ويحفظ محادثاتك وحجوزاتك ومجموعاتك.",
    "acc.no_account": "ليس لديك حساب؟", "acc.have_account": "لديك حساب؟", "acc.create_account": "أنشئ حساباً",
    "acc.username": "اسم المستخدم", "acc.username_hint": "من ٣ إلى ٢٤ حرفاً أو رقماً، ويظهر للآخرين في المجموعات. لا تستخدم اسمك الحقيقي.",
    "acc.password": "كلمة المرور", "acc.password_hint": "٨ أحرف على الأقل.", "acc.new_password": "كلمة المرور الجديدة",
    "acc.do_signin": "دخول", "acc.do_signup": "أنشئ الحساب",
    "acc.keep_note": "ما فعلته على هذا الجهاز قبل التسجيل يُحفظ في حسابك.",
    "acc.welcome": "أهلاً {u}", "acc.since": "معك منذ {d}",
    "acc.place": "مكاني", "acc.place_lead": "نعرض لك المجموعات والفعاليات القريبة منك أولاً.", "acc.country": "الدولة",
    "acc.city": "المدينة", "acc.any": "—", "acc.save": "حفظ", "acc.saved": "حُفظ.",
    "acc.about": "عنّي", "acc.about_lead": "اختر جنسك وفئتك العمرية لنقترح عليك المجموعات واللقاءات المناسبة. لا تظهر لأحد، والعمر فئة فقط لا تاريخ ميلاد. الدولة والمدينة اختياريتان.",
    "acc.choose": "اختر…", "acc.no_country": "اختر الدولة (اختياري)",
    "acc.complete_title": "أكمل بياناتك", "acc.complete_lead": "اختر جنسك وفئتك العمرية لنقترح عليك المجموعات واللقاءات المناسبة لك. لا تظهر لأحد.",
    "acc.lang": "اللغة", "acc.gender": "الجنس", "acc.gender_m": "ذكر", "acc.gender_f": "أنثى",
    "acc.age": "العمر", "acc.age.u18": "أقل من ١٨", "acc.age.18_24": "١٨ إلى ٢٤", "acc.age.25_34": "٢٥ إلى ٣٤",
    "acc.age.35_44": "٣٥ إلى ٤٤", "acc.age.45_54": "٤٥ إلى ٥٤", "acc.age.55p": "٥٥ فأكثر",
    "acc.age_minor": "إن كان عمرك أقل من ١٨ فاستأذن وليّ أمرك قبل الاتصال بداعية أو حضور لقاء.",
    "acc.chats": "محادثاتي مع المساعد", "acc.chats_lead": "المحادثات المحفوظة في حسابك: {n}. تراها على أي جهاز تدخل منه، وتحذف أيّاً منها من صفحة اسأل.",
    "acc.chats_none": "لا محادثات محفوظة بعد. ما تسأله وأنت داخل حسابك يُحفظ هنا.", "acc.chats_open": "افتح محادثاتي",
    "acc.chats_delete": "احذف كل المحادثات", "acc.chats_confirm": "نعم، احذفها من كل الأجهزة", "acc.chats_deleted": "حُذفت محادثاتك.",
    "acc.activity": "نشاطي", "acc.my_events": "فعالياتي", "acc.my_groups": "مجموعاتي",
    "acc.no_events": "لم تسجّل أو تنضم إلى فعالية بعد.", "acc.no_groups": "لم تنضم إلى مجموعة بعد.", "acc.browse": "تصفّح المجتمع",
    "acc.security": "الأمان", "acc.current_password": "كلمة المرور الحالية", "acc.change_password": "غيّر كلمة المرور",
    "acc.password_changed": "تغيّرت كلمة المرور.", "acc.signout": "خروج", "acc.signed_out": "خرجت من حسابك على هذا الجهاز.",
    "acc.delete": "حذف الحساب", "acc.delete_lead": "يحذف الحساب وكل ما فيه من أسئلة وحجوزات ومكالمات على كل الأجهزة، ولا يمكن التراجع.",
    "acc.delete_confirm": "اكتب كلمة المرور لتأكيد الحذف", "acc.do_delete": "احذف نهائياً", "acc.deleted": "حُذف حسابك.",
    "acc.err.username taken": "اسم المستخدم مأخوذ، جرّب غيره.",
    "acc.err.wrong username or password": "اسم المستخدم أو كلمة المرور غير صحيحة.",
    "acc.err.wrong username or recovery code": "اسم المستخدم أو رمز الاسترجاع غير صحيح.",
    "acc.err.wrong password": "كلمة المرور غير صحيحة.", "acc.err.too many attempts": "محاولات كثيرة. انتظر عشر دقائق ثم حاول.",
    "acc.err.invalid": "تأكد من اسم المستخدم (٣ إلى ٢٤ حرفاً أو رقماً) وكلمة المرور (٨ أحرف على الأقل).",
  },
  en: {
    "acc.email_optional": "Email (optional)", "acc.email_title": "Email for account recovery",
    "acc.email_hint": "Used only to send a code if you forget your password. Nobody else sees it. Without it, a forgotten password can't be recovered.",
    "acc.err.email taken": "That email is linked to another account.", "acc.err.wrong or expired code": "Wrong or expired code.",
    "acc.signin": "Sign in", "acc.signup": "New account", "acc.mine": "My account", "acc.signin_btn": "Sign in",
    "acc.signin_title": "Sign in", "acc.signin_lead": "Sign in to keep your chats and bookings on all your devices.",
    "acc.signup_title": "Create an account", "acc.signup_lead": "An account is optional. It keeps your chats, bookings and groups.",
    "acc.no_account": "Don't have an account?", "acc.have_account": "Already have an account?", "acc.create_account": "Create one",
    "acc.username": "Username", "acc.username_hint": "3 to 24 letters or digits. Others see it in groups, so don't use your real name.",
    "acc.password": "Password", "acc.password_hint": "At least 8 characters.", "acc.new_password": "New password",
    "acc.do_signin": "Sign in", "acc.do_signup": "Create account",
    "acc.keep_note": "What you did on this device before signing up is kept in your account.",
    "acc.welcome": "Welcome, {u}", "acc.since": "With us since {d}",
    "acc.place": "Where I am", "acc.place_lead": "Groups and events near you are shown first.", "acc.country": "Country",
    "acc.city": "City", "acc.any": "—", "acc.save": "Save", "acc.saved": "Saved.",
    "acc.about": "About me", "acc.about_lead": "Pick your sex and age band so we can suggest groups and meetups that fit you. Nobody else sees them, and age is a band, never a birth date. Country and city are optional.",
    "acc.choose": "Choose…", "acc.no_country": "Choose a country (optional)",
    "acc.complete_title": "Complete your profile", "acc.complete_lead": "Pick your sex and age band so we can suggest groups and meetups that fit you. Nobody else sees them.",
    "acc.lang": "Language", "acc.gender": "Sex", "acc.gender_m": "Male", "acc.gender_f": "Female",
    "acc.age": "Age", "acc.age.u18": "Under 18", "acc.age.18_24": "18 to 24", "acc.age.25_34": "25 to 34",
    "acc.age.35_44": "35 to 44", "acc.age.45_54": "45 to 54", "acc.age.55p": "55 or over",
    "acc.age_minor": "If you're under 18, ask a parent or guardian before calling a da'i or going to a meetup.",
    "acc.chats": "My chats with the assistant", "acc.chats_lead": "Chats saved to your account: {n}. You see them on any device you sign in on, and can delete any one of them on the Ask page.",
    "acc.chats_none": "No saved chats yet. What you ask while signed in is saved here.", "acc.chats_open": "Open my chats",
    "acc.chats_delete": "Delete all chats", "acc.chats_confirm": "Yes, delete them on every device", "acc.chats_deleted": "Your chats were deleted.",
    "acc.activity": "My activity", "acc.my_events": "My events", "acc.my_groups": "My groups",
    "acc.no_events": "You haven't registered for or joined an event yet.", "acc.no_groups": "You haven't joined a group yet.", "acc.browse": "Browse the community",
    "acc.security": "Security", "acc.current_password": "Current password", "acc.change_password": "Change password",
    "acc.password_changed": "Password changed.", "acc.signout": "Sign out", "acc.signed_out": "Signed out on this device.",
    "acc.delete": "Delete account", "acc.delete_lead": "Deletes the account and all its questions, bookings and calls on every device. This can't be undone.",
    "acc.delete_confirm": "Type your password to confirm", "acc.do_delete": "Delete for good", "acc.deleted": "Your account was deleted.",
    "acc.err.username taken": "That username is taken. Try another.",
    "acc.err.wrong username or password": "Wrong username or password.",
    "acc.err.wrong username or recovery code": "Wrong username or recovery code.",
    "acc.err.wrong password": "Wrong password.", "acc.err.too many attempts": "Too many attempts. Wait ten minutes and try again.",
    "acc.err.invalid": "Check the username (3 to 24 letters or digits) and the password (at least 8 characters).",
  },
});
