// RAG strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "src.verse": "آية", "src.hadith": "حديث", "src.term": "مصطلح", "src.qa": "سؤال وجواب", "src.open": "افتح المصدر",
    "src.qa_answer": "الجواب كما في الموسوعة", "src.ar_only": "هذا الجواب منشور بالعربية فقط في المصدر.",
    "src.bayyinat": "بيّنات", "src.short_answer": "مختصر الإجابة", "src.full_answer": "الجواب التفصيلي",
    "src.tafsir": "التفسير الميسر", "src.explanation": "الشرح",
    "src.no_en": "لا تتوفر ترجمة إنجليزية معتمدة لهذا الحديث في المصدر.", "src.rule": "ضابط الاستخدام",
    "ans.used": "المصادر التي أُجيب منها ({n})", "ans.cite": "المصدر {n}",
    "qc.title_exact": "النص يطابق المصحف", "qc.title_differs": "النص يختلف عن المصحف",
    "qc.title_ambiguous": "العبارة في أكثر من آية", "qc.title_not_found": "لم يُعثر على النص في المصحف",
    "qc.changed": "كلمة مختلفة", "qc.missing": "ناقص في نصك", "qc.extra": "زائد في نصك",
    "qc.quoted": "في نصك", "qc.reference": "في المصحف",
    "ocr.read": "قرأتُ من الصورة", "ocr.shows": "الصورة",
    "level.A": "معلومة أصلية مستقرة", "level.B": "شرح وتعريف", "level.C": "مسألة فيها تفصيل أو خلاف", "level.D": "حالة شخصية أو فتوى",
    "mode.sources_only": "وضع المصادر فقط",
    "ask.title": "اسأل عن الإسلام",
    "ask.lead": "اكتب ما يثير فضولك، أو أرفق صورة لنص رأيته.",
    "ask.placeholder": "اكتب سؤالك هنا…",
    "ask.photo": "أرفق صورة", "ask.remove_photo": "إزالة الصورة", "ask.send": "أرسل",
    "ask.thinking": "أبحث في المصادر المعتمدة…", "ask.reading": "أقرأ النص في الصورة…",
    "ask.helpful": "هل كانت الإجابة مفيدة؟", "ask.fb_yes": "مفيدة", "ask.fb_no": "غير مفيدة", "ask.thanks_fb": "شكراً، ملاحظتك تساعدنا على التحسين.",
    "ask.talk": "تحدّث مع داعية عن هذا", "ask.how": "كيف وصلتُ للإجابة؟",
    "ask.saved_note": "محادثاتك محفوظة في حسابك وتظهر على أي جهاز تدخل منه. تحذفها من صفحة حسابي.",
    "ask.clear": "محادثة جديدة", "ask.photo_attached": "صورة مرفقة",
    "ask.side_title": "كيف يجيب سَبِيلي؟",
    "ask.side_1": "يبحث في الحزمة العلمية المعتمدة فقط: نص المصحف والتفسير الميسر وترجمة رواد وموسوعة الأحاديث وموسوعتي الأسئلة والأجوبة وكتاب «بيّنات».",
    "ask.side_2": "يعرض نص الآية والحديث من المرجع كما هو، ولا يكتبه النموذج.",
    "ask.side_3": "إن لم يجد ما يكفي قال ذلك صراحة، ولا يصدر فتوى في حالتك الشخصية.",
    "ask.side_cta": "تفضّل الحديث مع إنسان؟",
    "ask.too_big": "حجم الصورة أكبر من 5 ميجابايت.",
    "ask.trace": "كيف وصلتُ للإجابة", "ask.trace_level": "مستوى المحتوى", "ask.trace_mode": "الوضع",
    "ask.trace_queries": "عبارات البحث", "ask.trace_found": "ما وجدته في المصادر", "ask.trace_time": "الوقت",
    "ask.trace_steps": "أين ذهب الوقت", "ask.step_ocr": "قراءة الصورة (النموذج)", "ask.step_analyze": "فهم السؤال (النموذج)",
    "ask.step_quote_check": "مطابقة النص بالمصحف", "ask.step_retrieve": "البحث في المصادر", "ask.step_bm25": "بحث الكلمات (BM25)",
    "ask.step_embed_query": "تمثيل السؤال (E5)", "ask.step_faiss": "بحث المعنى (FAISS)", "ask.step_fusion": "دمج النتائج",
    "ask.step_answer": "كتابة الإجابة (النموذج)", "ask.step_scripture_guard": "فحص النصوص والتوثيق", "ask.step_cards": "تجهيز البطاقات",
    "ask.trace_cited": "نسبة النص المسند", "ask.mode_ai": "شرح بالذكاء الاصطناعي مقيد بالمصادر",
    "ask.mode_sources": "عرض المصادر فقط (بلا توليد)", "ask.via_quote": "من مطابقة النص", "ask.via_glossary": "من قاموس المصطلحات", "ask.via_answer": "أقرب جواب معتمد في المعنى", "ask.via_meaning": "تشابه المعنى",
    "ask.s1": "لماذا يتجه المسلمون إلى الكعبة في صلاتهم؟",
    "ask.s2": "هل القرآن من تأليف محمد ﷺ؟",
    "ask.s3": "ما معنى التوحيد لشخص لم يسمع به من قبل؟",
    "ask.s4": "لماذا توجد أحكام مختلفة بين العلماء؟",
    "ask.s5": "ما أركان الإسلام؟",
    "ask.s6": "قل هو الله واحد الله الصمد",
  },
  en: {
    "src.verse": "Verse", "src.hadith": "Hadith", "src.term": "Term", "src.qa": "Q&A", "src.open": "Open source",
    "src.qa_answer": "The encyclopedia's answer", "src.ar_only": "The source publishes this answer in Arabic only.",
    "src.bayyinat": "Bayyinat", "src.short_answer": "Short answer", "src.full_answer": "Detailed answer",
    "src.tafsir": "At-Tafsir Al-Muyassar (Arabic)", "src.explanation": "Explanation",
    "src.no_en": "No approved English translation of this hadith is available in the source.", "src.rule": "Usage rule",
    "ans.used": "Sources this answer used ({n})", "ans.cite": "Source {n}",
    "qc.title_exact": "This text matches the Mushaf", "qc.title_differs": "This text differs from the Mushaf",
    "qc.title_ambiguous": "This phrase is in more than one verse", "qc.title_not_found": "Text not found in the Mushaf",
    "qc.changed": "Different word", "qc.missing": "Missing from your text", "qc.extra": "Extra in your text",
    "qc.quoted": "Your text", "qc.reference": "The Mushaf",
    "ocr.read": "Text I read in the photo", "ocr.shows": "The photo",
    "level.A": "Settled core information", "level.B": "Explanation", "level.C": "Detailed or disputed matter", "level.D": "Personal case or fatwa",
    "mode.sources_only": "Sources-only mode",
    "ask.title": "Ask about Islam",
    "ask.lead": "Ask whatever you're curious about, or attach a photo of a text you saw.",
    "ask.placeholder": "Type your question…",
    "ask.photo": "Attach a photo", "ask.remove_photo": "Remove photo", "ask.send": "Send",
    "ask.thinking": "Searching the approved sources…", "ask.reading": "Reading the text in your photo…",
    "ask.helpful": "Was this helpful?", "ask.fb_yes": "Helpful", "ask.fb_no": "Not helpful", "ask.thanks_fb": "Thank you, your feedback helps us improve.",
    "ask.talk": "Talk to a da'i about this", "ask.how": "How I found this",
    "ask.saved_note": "Your chats are saved to your account and show on any device you sign in on. Delete them from My account.",
    "ask.clear": "New conversation", "ask.photo_attached": "Photo attached",
    "ask.side_title": "How Sabeeli answers",
    "ask.side_1": "It searches only the approved scholarly package: the Mushaf, At-Tafsir Al-Muyassar, the Rowwad translation, the hadith encyclopedia, two Q&A encyclopedias and the book Bayyinat.",
    "ask.side_2": "Verse and hadith text is shown from the reference as published, never written by the model.",
    "ask.side_3": "If it can't find enough, it says so plainly, and it never gives a fatwa on your personal situation.",
    "ask.side_cta": "Prefer talking to a person?",
    "ask.too_big": "The photo is larger than 5 MB.",
    "ask.trace": "How I found this answer", "ask.trace_level": "Content level", "ask.trace_mode": "Mode",
    "ask.trace_queries": "Search phrases", "ask.trace_found": "What I found in the sources", "ask.trace_time": "Time",
    "ask.trace_steps": "Where the time went", "ask.step_ocr": "Reading the photo (model)", "ask.step_analyze": "Understanding the question (model)",
    "ask.step_quote_check": "Checking quotes against the Mushaf", "ask.step_retrieve": "Searching the sources", "ask.step_bm25": "Word search (BM25)",
    "ask.step_embed_query": "Embedding the question (E5)", "ask.step_faiss": "Meaning search (FAISS)", "ask.step_fusion": "Merging results",
    "ask.step_answer": "Writing the answer (model)", "ask.step_scripture_guard": "Checking scripture and citations", "ask.step_cards": "Preparing the cards",
    "ask.trace_cited": "Share of text with a source", "ask.mode_ai": "AI explanation limited to the sources",
    "ask.mode_sources": "Sources only (nothing generated)", "ask.via_quote": "from text matching", "ask.via_glossary": "from the glossary", "ask.via_answer": "closest approved answer in meaning", "ask.via_meaning": "meaning match",
    "ask.s1": "Why do Muslims face the Kaaba when they pray?",
    "ask.s2": "Did Muhammad ﷺ write the Quran?",
    "ask.s3": "What does Tawhid mean, for someone who's never heard of it?",
    "ask.s4": "Why do scholars sometimes give different rulings?",
    "ask.s5": "What are the pillars of Islam?",
    "ask.s6": "Is Islam against science?",
  },
});
