// RAG strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "src.verse": "آية", "src.hadith": "حديث", "src.term": "مصطلح", "src.open": "افتح المصدر",
    "src.tafsir": "التفسير الميسر", "src.explanation": "الشرح",
    "src.no_en": "لا تتوفر ترجمة إنجليزية معتمدة لهذا الحديث في المصدر.", "src.rule": "ضابط الاستخدام",
    "ans.sources": "المصادر ({n})", "ans.cite": "المصدر {n}",
    "qc.title_exact": "النص يطابق المصحف", "qc.title_differs": "النص يختلف عن المصحف",
    "qc.title_ambiguous": "العبارة في أكثر من آية", "qc.title_not_found": "لم يُعثر على النص في المصحف",
    "qc.changed": "كلمة مختلفة", "qc.missing": "ناقص في نصك", "qc.extra": "زائد في نصك",
    "qc.quoted": "في نصك", "qc.reference": "في المصحف",
    "ocr.read": "قرأتُ من الصورة", "ocr.shows": "الصورة",
    "level.A": "معلومة أصلية مستقرة", "level.B": "شرح وتعريف", "level.C": "مسألة فيها تفصيل أو خلاف", "level.D": "حالة شخصية أو فتوى",
    "mode.sources_only": "وضع المصادر فقط",
    "ask.title": "اسأل عن الإسلام",
    "ask.lead": "اكتب ما يثير فضولك، أو أرفق صورة لنص رأيته. تأتيك الإجابة من مصادر معتمدة مع إظهارها، وتستطيع الانتقال إلى داعية في أي وقت.",
    "ask.placeholder": "اكتب سؤالك هنا…",
    "ask.photo": "أرفق صورة", "ask.remove_photo": "إزالة الصورة", "ask.send": "أرسل",
    "ask.try": "جرّب أن تسأل",
    "ask.thinking": "أبحث في المصادر المعتمدة…", "ask.reading": "أقرأ النص في الصورة…",
    "ask.helpful": "هل كانت الإجابة مفيدة؟", "ask.fb_yes": "مفيدة", "ask.fb_no": "غير مفيدة", "ask.thanks_fb": "شكراً، ملاحظتك تساعدنا على التحسين.",
    "ask.talk": "تحدّث مع داعية عن هذا", "ask.how": "كيف وصلتُ للإجابة؟",
    "ask.clear": "محادثة جديدة", "ask.photo_attached": "صورة مرفقة",
    "ask.side_title": "كيف يجيب سَبِيلي؟",
    "ask.side_1": "يبحث في الحزمة العلمية المعتمدة فقط: نص المصحف والتفسير الميسر وترجمة رواد وموسوعة الأحاديث.",
    "ask.side_2": "يعرض نص الآية والحديث من المرجع كما هو، ولا يكتبه النموذج.",
    "ask.side_3": "إن لم يجد ما يكفي قال ذلك صراحة، ولا يصدر فتوى في حالتك الشخصية.",
    "ask.side_cta": "تفضّل الحديث مع إنسان؟",
    "ask.too_big": "حجم الصورة أكبر من 5 ميجابايت.",
    "ask.trace": "كيف وصلتُ للإجابة", "ask.trace_level": "مستوى المحتوى", "ask.trace_mode": "الوضع",
    "ask.trace_queries": "عبارات البحث", "ask.trace_found": "ما وجدته في المصادر", "ask.trace_time": "الوقت",
    "ask.trace_cited": "نسبة النص المسند", "ask.mode_ai": "شرح بالذكاء الاصطناعي مقيد بالمصادر",
    "ask.mode_sources": "عرض المصادر فقط (بلا توليد)", "ask.via_quote": "من مطابقة النص", "ask.via_glossary": "من قاموس المصطلحات",
    "ask.s1": "لماذا يتجه المسلمون إلى الكعبة في صلاتهم؟",
    "ask.s2": "هل القرآن من تأليف محمد ﷺ؟",
    "ask.s3": "ما معنى التوحيد لشخص لم يسمع به من قبل؟",
    "ask.s4": "لماذا توجد أحكام مختلفة بين العلماء؟",
    "ask.s5": "ما أركان الإسلام؟",
    "ask.s6": "قل هو الله واحد الله الصمد",
  },
  en: {
    "src.verse": "Verse", "src.hadith": "Hadith", "src.term": "Term", "src.open": "Open source",
    "src.tafsir": "At-Tafsir Al-Muyassar (Arabic)", "src.explanation": "Explanation",
    "src.no_en": "No approved English translation of this hadith is available in the source.", "src.rule": "Usage rule",
    "ans.sources": "Sources ({n})", "ans.cite": "Source {n}",
    "qc.title_exact": "This text matches the Mushaf", "qc.title_differs": "This text differs from the Mushaf",
    "qc.title_ambiguous": "This phrase is in more than one verse", "qc.title_not_found": "Text not found in the Mushaf",
    "qc.changed": "Different word", "qc.missing": "Missing from your text", "qc.extra": "Extra in your text",
    "qc.quoted": "Your text", "qc.reference": "The Mushaf",
    "ocr.read": "Text I read in the photo", "ocr.shows": "The photo",
    "level.A": "Settled core information", "level.B": "Explanation", "level.C": "Detailed or disputed matter", "level.D": "Personal case or fatwa",
    "mode.sources_only": "Sources-only mode",
    "ask.title": "Ask about Islam",
    "ask.lead": "Ask whatever you're curious about, or attach a photo of a text you saw. Answers come from approved sources, shown alongside, and you can move to a human guide at any time.",
    "ask.placeholder": "Type your question…",
    "ask.photo": "Attach a photo", "ask.remove_photo": "Remove photo", "ask.send": "Send",
    "ask.try": "Try asking",
    "ask.thinking": "Searching the approved sources…", "ask.reading": "Reading the text in your photo…",
    "ask.helpful": "Was this helpful?", "ask.fb_yes": "Helpful", "ask.fb_no": "Not helpful", "ask.thanks_fb": "Thank you, your feedback helps us improve.",
    "ask.talk": "Talk to a da'i about this", "ask.how": "How I found this",
    "ask.clear": "New conversation", "ask.photo_attached": "Photo attached",
    "ask.side_title": "How Sabeeli answers",
    "ask.side_1": "It searches only the approved scholarly package: the Mushaf, At-Tafsir Al-Muyassar, the Rowwad translation and the hadith encyclopedia.",
    "ask.side_2": "Verse and hadith text is shown from the reference as published, never written by the model.",
    "ask.side_3": "If it can't find enough, it says so plainly, and it never gives a fatwa on your personal situation.",
    "ask.side_cta": "Prefer talking to a person?",
    "ask.too_big": "The photo is larger than 5 MB.",
    "ask.trace": "How I found this answer", "ask.trace_level": "Content level", "ask.trace_mode": "Mode",
    "ask.trace_queries": "Search phrases", "ask.trace_found": "What I found in the sources", "ask.trace_time": "Time",
    "ask.trace_cited": "Share of text with a source", "ask.mode_ai": "AI explanation limited to the sources",
    "ask.mode_sources": "Sources only (nothing generated)", "ask.via_quote": "from text matching", "ask.via_glossary": "from the glossary",
    "ask.s1": "Why do Muslims face the Kaaba when they pray?",
    "ask.s2": "Did Muhammad ﷺ write the Quran?",
    "ask.s3": "What does Tawhid mean, for someone who's never heard of it?",
    "ask.s4": "Why do scholars sometimes give different rulings?",
    "ask.s5": "What are the pillars of Islam?",
    "ask.s6": "Is Islam against science?",
  },
});
