// Community strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "com.title": "المجتمع", "com.lead": "تابع تعلّمك مع آخرين في مجموعات يقودها دعاة، واحضر فعاليات في أماكن عامة أو عن بُعد. بلا رسائل خاصة بين الأعضاء، وبأسماء مستعارة.",
    "com.groups": "المجموعات", "com.meetups": "فعاليات المجتمع المسلم", "com.all_langs": "كل اللغات",
    // Counted text (tn): Arabic has a form for 0, 1, 2, 3–10, 11–99; the plain key is the form for 100 and more.
    "com.members": "{n} عضو", "com.members.zero": "لا أعضاء بعد", "com.members.one": "عضو واحد", "com.members.two": "عضوان",
    "com.members.few": "{n} أعضاء", "com.members.many": "{n} عضواً",
    "com.led_by": "يقودها {name}", "com.join": "انضم", "com.open": "ادخل المجموعة",
    "com.women": "للنساء", "com.men": "للرجال", "com.families": "للعائلات", "com.everyone": "للجميع",
    "com.join_title": "الانضمام إلى «{title}»", "com.nickname": "اسم مستعار يظهر للأعضاء", "com.nick_hint": "لا تستخدم اسمك الحقيقي أو أي معلومة تعرّف بك.",
    "com.rules": "قواعد المجموعة",
    "com.rule1": "الاحترام والرفق في الحوار، والسؤال مرحب به دائماً.",
    "com.rule2": "لا رسائل خاصة، ولا روابط، ولا أرقام هواتف أو حسابات.",
    "com.rule3": "المساعد «@سبيلي» يجيب من المصادر المعتمدة، والداعية يراجع ويوضح.",
    "com.rule4": "الإساءة تُحجب، وتكرارها يوقف المشاركة.",
    "com.accept": "قرأت القواعد وأوافق عليها", "com.joined": "انضممت إلى المجموعة",
    "com.empty_groups": "لا توجد مجموعات بهذا الاختيار بعد.", "com.empty_meetups": "لا توجد فعاليات قادمة.",
    "com.n_groups": "{n} مجموعة", "com.n_groups.zero": "لا مجموعات", "com.n_groups.one": "مجموعة واحدة", "com.n_groups.two": "مجموعتان",
    "com.n_groups.few": "{n} مجموعات", "com.n_groups.many": "{n} مجموعة",
    "com.n_meetups": "{n} فعالية", "com.n_meetups.zero": "لا فعاليات", "com.n_meetups.one": "فعالية واحدة", "com.n_meetups.two": "فعاليتان",
    "com.n_meetups.few": "{n} فعاليات", "com.n_meetups.many": "{n} فعالية",
    "com.clear_filters": "مسح الفلاتر", "com.filters": "الفلاتر", "com.lang": "اللغة",
    "com.spots": "بقي {n} مقعد", "com.spots.zero": "لا مقاعد متبقية", "com.spots.one": "بقي مقعد واحد", "com.spots.two": "بقي مقعدان",
    "com.spots.few": "بقيت {n} مقاعد", "com.spots.many": "بقي {n} مقعداً",
    "com.full": "اكتمل العدد", "com.host": "يقدمه {name}",
    "com.rsvp": "احجز مقعداً", "com.rsvp_title": "احجز مقعدك في «{title}»", "com.rsvp_note": "لا نطلب اسمك أو رقمك. ستحصل على رمز حجز تُظهره عند الحضور.",
    "com.confirm_aud": "أؤكد أن هذه الفعالية تناسبني ({aud})", "com.booked": "حُجز مقعدك", "com.code": "رمز الحجز",
    "com.add_cal": "أضف إلى التقويم", "com.cancel_rsvp": "إلغاء الحجز", "com.public_place": "مكان عام",
    "com.minutes": "{n} دقيقة", "com.minutes.one": "دقيقة واحدة", "com.minutes.two": "دقيقتان", "com.minutes.few": "{n} دقائق",
    "com.reg.required": "بحجز", "com.reg.open": "دون حجز", "com.reg.all": "كل الفعاليات",
    "com.walk_in": "لا يلزم الحجز: احضر مباشرة", "com.reg_needed": "يلزم الحجز", "com.country": "الدولة", "com.city": "المنطقة", "com.all_countries": "كل الدول", "com.all_cities": "كل المناطق", "com.age": "الفئة العمرية",
    "com.age.all": "كل الأعمار", "com.age.kids": "أطفال مع ولي أمرهم", "com.age.youth": "شباب ١٨–٢٩",
    "com.age.adults": "بالغون ٣٠–٥٩", "com.age.seniors": "كبار ٦٠ فأكثر",
    "com.open_to": "متاحة لـ", "com.for.all": "الكل", "com.for.women": "النساء", "com.for.men": "الرجال",
    "com.mine": "أنشطتي", "com.format": "نوع الفعالية", "com.fmt.all": "الكل", "com.fmt.in_person": "حضوري", "com.fmt.online": "عن بُعد",
    "com.online_place": "عن بُعد: يظهر الرابط بعد الحجز", "com.online_booked": "عن بُعد: افتح رابط اللقاء في موعده", "com.online_everywhere": "الفعاليات عن بُعد تظهر مع كل الدول.",
    "com.city_time": "بتوقيت {city}", "com.happening_now": "يجري الآن", "com.ended": "انتهى", "com.cancelled_by_host": "ألغاه المضيف",
    "com.spots_few": "بقي {n} مقعد فقط", "com.spots_few.one": "بقي مقعد واحد فقط", "com.spots_few.two": "بقي مقعدان فقط",
    "com.spots_few.few": "بقيت {n} مقاعد فقط", "com.spots_few.many": "بقي {n} مقعداً فقط",
    "com.youre_in": "أنت مسجّل", "com.join_now": "ادخل اللقاء الآن", "com.open_link": "رابط اللقاء",
    "com.cancel_q": "إلغاء حجزك؟", "com.cancel_yes": "نعم، ألغِه", "com.cancel_keep": "لا، أبقِه",
    "com.cancelled_toast": "أُلغي حجزك.", "com.left_toast": "انسحبت من الفعالية.",
    "com.rsvp_note_online": "لا نطلب اسمك أو رقمك. يظهر رابط اللقاء بعد الحجز، وتجده دائماً في «أنشطتي».",
    "com.rsvp_note_open": "لا يلزم حجز: احضر مباشرة. انضمامك يضيفه إلى «أنشطتي» ويعرّف المضيف بعدد الحضور.",
    "com.confirm_booking": "تأكيد الحجز", "com.confirm_join": "تأكيد الانضمام", "com.joined_title": "أنت ضمن الحضور",
    "com.next_code": "أظهر هذا الرمز عند الدخول. تجده أيضاً في «أنشطتي».",
    "com.next_open": "لا تحتاج رمزاً: احضر في الموعد. التفاصيل في «أنشطتي».",
    "com.next_online": "افتح الرابط في موعد الفعالية، وتجده دائماً في «أنشطتي».",
    "com.see_mine": "اذهب إلى أنشطتي", "com.mine_device": "حجوزاتك محفوظة في هذا المتصفح.", "com.mine_signin": "سجّل الدخول لتجدها على أي جهاز.",
    "com.mine_upcoming": "القادمة", "com.mine_none": "لم تحجز أي فعالية بعد.", "com.browse_events": "تصفح الفعاليات",
    "com.mine_groups": "مجموعاتك", "com.mine_no_groups": "لم تنضم إلى مجموعة بعد.", "com.browse_groups": "تصفح المجموعات",
    "com.mine_past": "السابقة والملغاة ({n})",
    "com.online_url": "رابط اللقاء", "com.online_url_hint": "رابط Zoom أو Google Meet أو Teams يبدأ بـ https://. لا يراه إلا من حجز.",
    "com.tz_note": "الوقت بتوقيت جهازك: {tz}.",
    "err.an online meetup needs an https meeting link": "أضف رابط لقاء يبدأ بـ https://",
    "err.a meetup in person needs a city and a venue": "أضف المدينة ومكان الفعالية.",
    "err.a meetup for children must be in person": "فعاليات الأطفال حضورية فقط، مع ولي الأمر.",
    "com.leave_q": "الانسحاب من هذه الفعالية؟", "com.leave_yes": "نعم، انسحب",
    "com.tz_label": "المنطقة الزمنية", "com.tz_venue": "اكتب الوقت كما هو في مكان الفعالية: {tz}.",
    // cities in countries with several time zones: "(New York time)" and the da'i's time zone picker
    "com.zone.America/New_York": "نيويورك", "com.zone.America/Chicago": "شيكاغو", "com.zone.America/Denver": "دنفر", "com.zone.America/Phoenix": "فينيكس",
    "com.zone.America/Los_Angeles": "لوس أنجلوس", "com.zone.America/Anchorage": "أنكوريج", "com.zone.Pacific/Honolulu": "هونولولو", "com.zone.America/Toronto": "تورونتو",
    "com.zone.America/Halifax": "هاليفاكس", "com.zone.America/St_Johns": "سانت جونز", "com.zone.America/Winnipeg": "وينيبيغ", "com.zone.America/Regina": "ريجاينا",
    "com.zone.America/Edmonton": "إدمونتون", "com.zone.America/Vancouver": "فانكوفر", "com.zone.Australia/Sydney": "سيدني", "com.zone.Australia/Brisbane": "بريزبن",
    "com.zone.Australia/Adelaide": "أديلايد", "com.zone.Australia/Darwin": "داروين", "com.zone.Australia/Perth": "بيرث", "com.zone.Australia/Hobart": "هوبارت",
    "com.zone.Asia/Jakarta": "جاكرتا", "com.zone.Asia/Makassar": "ماكاسار", "com.zone.Asia/Jayapura": "جايابورا",
    "com.series.qawl_amal": "القول والعمل في الإسلام", "com.series_lead.qawl_amal": "سلسلة تربط ما نتعلمه بما نعمله: درس قصير ثم تطبيق عملي مع الآخرين.", "com.series.ramadan": "فعاليات رمضان", "com.series_lead.ramadan": "إفطارات جماعية وليالٍ تعريفية في رمضان، مفتوحة للجميع.", "com.register": "احجز", "com.join_event": "انضم", "com.joined_event": "انضممت", "com.leave_event": "إلغاء الانضمام", "com.joined_toast": "انضممت إلى الفعالية.", "com.join_title_event": "الانضمام إلى «{title}»", "com.guest": "زائر",
    "com.going": "{n} منضم", "com.going.zero": "لا منضمين بعد", "com.going.one": "منضم واحد", "com.going.two": "منضمان",
    "com.going.few": "{n} منضمين", "com.going.many": "{n} منضماً",
    "com.confirm_guardian": "أنا ولي أمر الطفل وسأحضر معه طوال الفعالية",
    "gr.report": "إبلاغ", "gr.report_q": "إبلاغ قائد المجموعة عن هذه الرسالة؟", "gr.reported_toast": "شكراً، أبلغنا قائد المجموعة ليراجعها.",
    "gr.reported": "أبلغ عنها عضو", "gr.delete": "حذف", "gr.delete_q": "حذف رسالتك؟", "gr.deleted_toast": "حُذفت رسالتك.",
    "gr.new_msgs": "رسائل جديدة", "gr.count": "{n} / {max}", "gr.feed": "رسائل المجموعة",
    "ev.back": "كل الفعاليات", "ev.not_found": "لم نجد هذه الفعالية، وربما أُلغيت.",
    "gr.back": "كل المجموعات", "gr.leave": "مغادرة المجموعة", "gr.ph": "اكتب رسالة… واكتب @سبيلي لتسأل المساعد",
    "gr.ask_bot": "اسأل @سبيلي", "gr.leader": "قائد المجموعة", "gr.bot": "مساعد آلي",
    "gr.deleted": "حُذفت هذه الرسالة.", "gr.bot_thinking": "سَبِيلي يبحث في المصادر…", "gr.needs_leader": "بانتظار توضيح الداعية",
    "gr.muted": "أُوقفت مشاركتك في هذه المجموعة.", "gr.err.abuse": "لم تُنشر الرسالة لأنها تحتوي ألفاظاً مسيئة.",
    "gr.err.too_fast": "مهلاً، انتظر ثوانٍ قبل الرسالة التالية.", "gr.err.too_long": "الرسالة طويلة جداً.",
    "gr.redacted": "أخفينا روابط أو معلومات تواصل من رسالتك حفاظاً على الخصوصية.", "gr.not_member": "انضم إلى المجموعة لتقرأ رسائلها وتشارك.",
    "gr.rules": "القواعد", "gr.you": "أنت",
    "gr.leave_q": "مغادرة هذه المجموعة؟", "gr.leave_yes": "غادر", "gr.leave_stay": "ابقَ", "gr.left": "غادرت المجموعة.",
    "gr.empty": "لا رسائل بعد. كن أول من يسأل.", "gr.not_found": "لم نجد هذه المجموعة، وربما أُغلقت.",
    "com.confirm_group_aud": "أؤكد أن هذه المجموعة تناسبني ({aud})",
    "err.please confirm the audience of this group": "يرجى تأكيد أن المجموعة تناسبك.",
    "err.meetup already started": "بدأت الفعالية، ولم يعد الحجز متاحاً.",
    "err.the meetup must start in the future": "اختر موعداً لم يأتِ بعد.",
      "gnm.title": "مبارك!", "gnm.lead": "سجّل الداعية {name} أنك أسلمت في مكالمتكما. نسأل الله لك الثبات.",
    "gnm.lead_anon": "سجّل الداعية أنك أسلمت في مكالمتكما. نسأل الله لك الثبات.",
    "gnm.ask": "هل تحب أن نشارك هذه البشرى في مجموعاتك؟",
    "gnm.what_groups": "ستُنشر رسالة ترحيب واحدة في {groups}، ويظهر وسم «مسلم جديد» بجانب اسمك المستعار.",
    "gnm.what_none": "لست في أي مجموعة الآن. إن وافقت، يظهر وسم «مسلم جديد» بجانب اسمك المستعار حين تنضم إلى مجموعة.",
    "gnm.your_choice": "الأمر لك. إن لم ترغب، لن يُعلَن شيء ونحذف هذا التسجيل. ويمكنك إخفاء الوسم لاحقاً متى شئت.",
    "gnm.share": "نعم، شارك البشرى", "gnm.keep": "لا، أبقِها لي",
    "gnm.shared_done": "شاركنا البشرى في مجموعاتك. حيّاك الله!", "gnm.removed_done": "لم نشارك شيئاً وحذفنا التسجيل.",
    "gnm.badge": "مسلم جديد", "gnm.shared_state": "يظهر هذا الوسم بجانب اسمك المستعار في المجموعات.",
    "gnm.remove": "إخفاء الوسم", "gnm.remove_q": "نخفي الوسم ونحذف رسائل الترحيب من مجموعاتك؟", "gnm.remove_yes": "نعم، أخفِه",
  },
  en: {
    "gnm.title": "Congratulations!", "gnm.lead": "Your da'i {name} noted that you embraced Islam in your call. May Allah keep you steadfast.",
    "gnm.lead_anon": "Your da'i noted that you embraced Islam in your call. May Allah keep you steadfast.",
    "gnm.ask": "Would you like us to share the good news in your groups?",
    "gnm.what_groups": "One welcome message will be posted in {groups}, and a \"New Muslim\" badge will show next to your nickname.",
    "gnm.what_none": "You're not in any group yet. If you agree, a \"New Muslim\" badge will show next to your nickname when you join one.",
    "gnm.your_choice": "It's your choice. If you'd rather not, nothing is announced and we delete this record. You can also hide the badge later at any time.",
    "gnm.share": "Yes, share the news", "gnm.keep": "No, keep it to myself",
    "gnm.shared_done": "We shared the news in your groups. Welcome!", "gnm.removed_done": "Nothing was shared, and the record was deleted.",
    "gnm.badge": "New Muslim", "gnm.shared_state": "This badge shows next to your nickname in groups.",
    "gnm.remove": "Hide the badge", "gnm.remove_q": "Hide the badge and delete the welcome messages from your groups?", "gnm.remove_yes": "Yes, hide it",
    "com.title": "Community", "com.lead": "Keep learning with others in groups led by da'is, and join events at public venues or online. No private messages between members, and nicknames only.",
    "com.groups": "Groups", "com.meetups": "Muslim community events", "com.all_langs": "All languages",
    "com.members": "{n} members", "com.members.one": "{n} member", "com.led_by": "Led by {name}", "com.join": "Join", "com.open": "Open group",
    "com.women": "Women", "com.men": "Men", "com.families": "Families", "com.everyone": "Everyone",
    "com.join_title": "Join “{title}”", "com.nickname": "A nickname other members will see", "com.nick_hint": "Don't use your real name or anything that identifies you.",
    "com.rules": "Group rules",
    "com.rule1": "Be respectful and kind; every question is welcome.",
    "com.rule2": "No private messages, links, phone numbers or account handles.",
    "com.rule3": "The assistant (@sabeeli) answers from approved sources; the da'i reviews and clarifies.",
    "com.rule4": "Abuse is blocked, and repeated abuse stops participation.",
    "com.accept": "I've read the rules and agree", "com.joined": "You joined the group",
    "com.empty_groups": "No groups match these filters yet.", "com.empty_meetups": "No upcoming events.",
    "com.n_groups": "{n} groups", "com.n_groups.one": "{n} group", "com.n_meetups": "{n} events", "com.n_meetups.one": "{n} event", "com.clear_filters": "Clear filters", "com.filters": "Filters", "com.lang": "Language",
    "com.spots": "{n} spots left", "com.spots.one": "{n} spot left", "com.full": "Full", "com.host": "Hosted by {name}",
    "com.rsvp": "Book a spot", "com.rsvp_title": "Book a spot at “{title}”", "com.rsvp_note": "We don't ask for your name or number. You'll get a booking code to show when you arrive.",
    "com.confirm_aud": "I confirm this event is for me ({aud})", "com.booked": "Your spot is booked", "com.code": "Booking code",
    "com.add_cal": "Add to calendar", "com.cancel_rsvp": "Cancel booking", "com.public_place": "Public venue",
    "com.minutes": "{n} min",
    "com.reg.required": "Booking needed", "com.reg.open": "Walk-in", "com.reg.all": "All events",
    "com.walk_in": "No booking needed: just come", "com.reg_needed": "Booking required", "com.country": "Country", "com.city": "Region", "com.all_countries": "All countries", "com.all_cities": "All regions", "com.age": "Age group",
    "com.age.all": "All ages", "com.age.kids": "Children with a guardian", "com.age.youth": "Youth 18–29",
    "com.age.adults": "Adults 30–59", "com.age.seniors": "Seniors 60+",
    "com.open_to": "Open to", "com.for.all": "All", "com.for.women": "Women", "com.for.men": "Men",
    "com.mine": "My activities", "com.format": "Format", "com.fmt.all": "All", "com.fmt.in_person": "In person", "com.fmt.online": "Online",
    "com.online_place": "Online: the link appears once you book", "com.online_booked": "Online: open the meeting link at the start time", "com.online_everywhere": "Online events show for every country.",
    "com.city_time": "{city} time", "com.happening_now": "Happening now", "com.ended": "Ended", "com.cancelled_by_host": "Cancelled by the host",
    "com.spots_few": "Only {n} spots left", "com.spots_few.one": "Only {n} spot left", "com.youre_in": "You're in", "com.join_now": "Join now", "com.open_link": "Meeting link",
    "com.cancel_q": "Cancel your booking?", "com.cancel_yes": "Yes, cancel", "com.cancel_keep": "Keep it",
    "com.cancelled_toast": "Your booking was cancelled.", "com.left_toast": "You left the event.",
    "com.rsvp_note_online": "We don't ask for your name or number. The meeting link appears once you book, and stays under My activities.",
    "com.rsvp_note_open": "No booking needed: just come. Joining adds it to My activities and tells the host how many to expect.",
    "com.confirm_booking": "Confirm booking", "com.confirm_join": "Confirm", "com.joined_title": "You're on the list",
    "com.next_code": "Show this code at the entrance. It's also under My activities.",
    "com.next_open": "No code needed: just come on time. The details are under My activities.",
    "com.next_online": "Open the link at the start time. You'll always find it under My activities.",
    "com.see_mine": "Go to My activities", "com.mine_device": "Your bookings are saved in this browser.", "com.mine_signin": "Sign in to see them on any device.",
    "com.mine_upcoming": "Coming up", "com.mine_none": "You haven't booked any events yet.", "com.browse_events": "Browse events",
    "com.mine_groups": "Your groups", "com.mine_no_groups": "You haven't joined a group yet.", "com.browse_groups": "Browse groups",
    "com.mine_past": "Past and cancelled ({n})",
    "com.online_url": "Meeting link", "com.online_url_hint": "A Zoom, Google Meet or Teams link starting with https://. Only people who book see it.",
    "com.tz_note": "In your device's time zone: {tz}.",
    "err.an online meetup needs an https meeting link": "Add a meeting link starting with https://",
    "err.a meetup in person needs a city and a venue": "Add the city and the venue.",
    "err.a meetup for children must be in person": "Events for children are in person only, with a guardian.",
    "com.leave_q": "Leave this event?", "com.leave_yes": "Yes, leave",
    "com.tz_label": "Time zone", "com.tz_venue": "Enter the time as it is at the venue: {tz}.",
    // cities in countries with several time zones: "(New York time)" and the da'i's time zone picker
    "com.zone.America/New_York": "New York", "com.zone.America/Chicago": "Chicago", "com.zone.America/Denver": "Denver", "com.zone.America/Phoenix": "Phoenix",
    "com.zone.America/Los_Angeles": "Los Angeles", "com.zone.America/Anchorage": "Anchorage", "com.zone.Pacific/Honolulu": "Honolulu", "com.zone.America/Toronto": "Toronto",
    "com.zone.America/Halifax": "Halifax", "com.zone.America/St_Johns": "St. John's", "com.zone.America/Winnipeg": "Winnipeg", "com.zone.America/Regina": "Regina",
    "com.zone.America/Edmonton": "Edmonton", "com.zone.America/Vancouver": "Vancouver", "com.zone.Australia/Sydney": "Sydney", "com.zone.Australia/Brisbane": "Brisbane",
    "com.zone.Australia/Adelaide": "Adelaide", "com.zone.Australia/Darwin": "Darwin", "com.zone.Australia/Perth": "Perth", "com.zone.Australia/Hobart": "Hobart",
    "com.zone.Asia/Jakarta": "Jakarta", "com.zone.Asia/Makassar": "Makassar", "com.zone.Asia/Jayapura": "Jayapura",
    "com.series.qawl_amal": "Word and Deed in Islam", "com.series_lead.qawl_amal": "A series linking what we learn with what we do: a short lesson, then putting it into practice together.", "com.series.ramadan": "Ramadan events", "com.series_lead.ramadan": "Shared iftars and open evenings in Ramadan, open to everyone.", "com.register": "Book", "com.join_event": "Join", "com.joined_event": "Joined", "com.leave_event": "Leave", "com.joined_toast": "You joined the event.", "com.join_title_event": "Join “{title}”", "com.going": "{n} going", "com.guest": "Guest",
    "com.confirm_guardian": "I am the child's guardian and will stay with them throughout",
    "gr.report": "Report", "gr.report_q": "Report this message to the group leader?", "gr.reported_toast": "Thanks. We've asked the group leader to review it.",
    "gr.reported": "Reported by a member", "gr.delete": "Delete", "gr.delete_q": "Delete your message?", "gr.deleted_toast": "Your message was deleted.",
    "gr.new_msgs": "New messages", "gr.count": "{n} / {max}", "gr.feed": "Group messages",
    "ev.back": "All events", "ev.not_found": "We couldn't find this event. It may have been removed.",
    "gr.back": "All groups", "gr.leave": "Leave group", "gr.ph": "Write a message… tag @sabeeli to ask the assistant",
    "gr.ask_bot": "Ask @sabeeli", "gr.leader": "Group leader", "gr.bot": "AI assistant",
    "gr.deleted": "This message was removed.", "gr.bot_thinking": "Sabeeli is searching the sources…", "gr.needs_leader": "Waiting for the da'i to clarify",
    "gr.muted": "Your participation in this group is paused.", "gr.err.abuse": "Not posted: the message contains abusive language.",
    "gr.err.too_fast": "Slow down a little before the next message.", "gr.err.too_long": "The message is too long.",
    "gr.redacted": "We hid links or contact details from your message to protect privacy.", "gr.not_member": "Join the group to read and take part.",
    "gr.rules": "Rules", "gr.you": "You",
    "gr.leave_q": "Leave this group?", "gr.leave_yes": "Leave", "gr.leave_stay": "Stay", "gr.left": "You left the group.",
    "gr.empty": "No messages yet. Be the first to ask.", "gr.not_found": "We couldn't find this group. It may have been closed.",
    "com.confirm_group_aud": "I confirm this group is for me ({aud})",
    "err.please confirm the audience of this group": "Please confirm this group is for you.",
    "err.meetup already started": "This event has started; booking is closed.",
    "err.the meetup must start in the future": "Choose a time that hasn't passed yet.",
    },
});
