// Community strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "com.title": "المجتمع", "com.lead": "تابع تعلّمك مع آخرين في مجموعات يقودها دعاة، واحضر لقاءات في أماكن عامة. بلا رسائل خاصة بين الأعضاء، وبأسماء مستعارة.",
    "com.groups": "المجموعات", "com.meetups": "فعاليات المجتمع المسلم", "com.all_langs": "كل اللغات",
    "com.members": "{n} عضو", "com.led_by": "يقودها {name}", "com.join": "انضم", "com.open": "ادخل المجموعة",
    "com.women": "للنساء", "com.men": "للرجال", "com.families": "للعائلات", "com.everyone": "للجميع",
    "com.join_title": "الانضمام إلى «{title}»", "com.nickname": "اسم مستعار يظهر للأعضاء", "com.nick_hint": "لا تستخدم اسمك الحقيقي أو أي معلومة تعرّف بك.",
    "com.rules": "قواعد المجموعة",
    "com.rule1": "الاحترام والرفق في الحوار، والسؤال مرحب به دائماً.",
    "com.rule2": "لا رسائل خاصة، ولا روابط، ولا أرقام هواتف أو حسابات.",
    "com.rule3": "المساعد «@سبيلي» يجيب من المصادر المعتمدة، والداعية يراجع ويوضح.",
    "com.rule4": "الإساءة تُحجب، وتكرارها يوقف المشاركة.",
    "com.accept": "قرأت القواعد وأوافق عليها", "com.joined": "انضممت إلى المجموعة",
    "com.empty_groups": "لا توجد مجموعات بهذا الاختيار بعد.", "com.empty_meetups": "لا توجد فعاليات قادمة.",
    "com.spots": "{n} مقعد متبقٍ", "com.full": "اكتمل العدد", "com.host": "يقدمه {name}",
    "com.rsvp": "احجز مقعداً", "com.rsvp_title": "التسجيل في «{title}»", "com.rsvp_note": "لا نطلب اسمك أو رقمك. ستحصل على رمز حجز تُظهره عند الحضور.",
    "com.confirm_aud": "أؤكد أن هذا اللقاء يناسبني ({aud})", "com.booked": "حُجز مقعدك", "com.code": "رمز الحجز",
    "com.add_cal": "أضف إلى التقويم", "com.cancel_rsvp": "إلغاء الحجز", "com.public_place": "مكان عام",
    "com.minutes": "{n} دقيقة",
    "com.reg.required": "بتسجيل", "com.reg.open": "دون تسجيل", "com.reg.all": "كل الفعاليات",
    "com.walk_in": "لا يلزم التسجيل: احضر مباشرة", "com.reg_needed": "يلزم التسجيل", "com.country": "الدولة", "com.city": "المنطقة", "com.all_countries": "كل الدول", "com.all_cities": "كل المناطق", "com.age": "الفئة العمرية",
    "com.age.all": "كل الأعمار", "com.age.kids": "أطفال مع ولي أمرهم", "com.age.youth": "شباب ١٨–٢٩",
    "com.age.adults": "بالغون ٣٠–٥٩", "com.age.seniors": "كبار ٦٠ فأكثر",
    "com.open_to": "متاحة لـ", "com.for.all": "الكل", "com.for.women": "النساء", "com.for.men": "الرجال",
    "com.mine": "أنشطتي", "com.format": "نوع اللقاء", "com.fmt.all": "الكل", "com.fmt.in_person": "حضوري", "com.fmt.online": "عن بُعد",
    "com.online_place": "عن بُعد: يظهر الرابط بعد الحجز", "com.online_booked": "عن بُعد: ادخل من «رابط اللقاء» في موعده", "com.online_everywhere": "اللقاءات عن بُعد تظهر مع كل الدول.",
    "com.city_time": "بتوقيت {city}", "com.happening_now": "يجري الآن", "com.ended": "انتهى", "com.cancelled_by_host": "ألغاه المضيف",
    "com.spots_few": "بقي {n} مقاعد فقط", "com.youre_in": "أنت مسجّل", "com.join_now": "ادخل اللقاء الآن", "com.open_link": "رابط اللقاء",
    "com.cancel_q": "إلغاء حجزك؟", "com.cancel_yes": "نعم، ألغِه", "com.cancel_keep": "لا، أبقِه",
    "com.rsvp_note_online": "لا نطلب اسمك أو رقمك. يظهر رابط اللقاء بعد الحجز، وتجده دائماً في «أنشطتي».",
    "com.rsvp_note_open": "لا يلزم حجز: احضر مباشرة. انضمامك يضيفه إلى «أنشطتي» ويعرّف المضيف بعدد الحضور.",
    "com.confirm_booking": "تأكيد الحجز", "com.confirm_join": "تأكيد الانضمام", "com.joined_title": "أنت ضمن الحضور",
    "com.next_code": "أظهر هذا الرمز عند الدخول. تجده أيضاً في «أنشطتي».",
    "com.next_open": "لا تحتاج رمزاً: احضر في الموعد. التفاصيل في «أنشطتي».",
    "com.next_online": "افتح الرابط في موعد اللقاء. تجده أيضاً في «أنشطتي»، ويظهر زر الدخول قبل البدء بربع ساعة.",
    "com.see_mine": "اذهب إلى أنشطتي", "com.mine_device": "حجوزاتك محفوظة في هذا المتصفح.", "com.mine_signin": "سجّل الدخول لتجدها على أي جهاز.",
    "com.mine_upcoming": "القادمة", "com.mine_none": "لم تحجز أي لقاء بعد.", "com.browse_events": "تصفح الفعاليات",
    "com.mine_groups": "مجموعاتك", "com.mine_no_groups": "لم تنضم إلى مجموعة بعد.", "com.browse_groups": "تصفح المجموعات",
    "com.mine_past": "السابقة والملغاة ({n})",
    "com.online_url": "رابط اللقاء", "com.online_url_hint": "رابط Zoom أو Google Meet أو Teams يبدأ بـ https://. لا يراه إلا من حجز.",
    "com.tz_note": "الوقت بتوقيت جهازك ({tz}).",
    "err.an online meetup needs an https meeting link": "أضف رابط لقاء يبدأ بـ https://",
    "err.a meetup in person needs a city and a venue": "أضف المدينة ومكان اللقاء.",
    "com.series.qawl_amal": "القول والعمل في الإسلام", "com.series_lead.qawl_amal": "سلسلة تربط ما نتعلمه بما نعمله: درس قصير ثم تطبيق عملي مع الآخرين.", "com.series.ramadan": "فعاليات رمضان", "com.series_lead.ramadan": "إفطارات جماعية وليالٍ تعريفية في رمضان، مفتوحة للجميع.", "com.register": "سجّل", "com.join_event": "انضم", "com.joined_event": "انضممت", "com.leave_event": "إلغاء الانضمام", "com.joined_toast": "انضممت إلى الفعالية.", "com.join_title_event": "الانضمام إلى «{title}»", "com.going": "{n} منضم", "com.guest": "زائر",
    "com.confirm_guardian": "أنا ولي أمر الطفل وسأحضر معه طوال اللقاء",
    "gr.back": "كل المجموعات", "gr.leave": "مغادرة المجموعة", "gr.ph": "اكتب رسالة… واكتب @سبيلي لتسأل المساعد",
    "gr.ask_bot": "اسأل @سبيلي", "gr.leader": "قائد المجموعة", "gr.bot": "مساعد آلي",
    "gr.deleted": "حُذفت هذه الرسالة.", "gr.bot_thinking": "سَبِيلي يبحث في المصادر…", "gr.needs_leader": "بانتظار توضيح الداعية",
    "gr.muted": "أُوقفت مشاركتك في هذه المجموعة.", "gr.err.abuse": "لم تُنشر الرسالة لأنها تحتوي ألفاظاً مسيئة.",
    "gr.err.too_fast": "مهلاً، انتظر ثوانٍ قبل الرسالة التالية.", "gr.err.too_long": "الرسالة طويلة جداً.",
    "gr.redacted": "أخفينا روابط أو معلومات تواصل من رسالتك حفاظاً على الخصوصية.", "gr.not_member": "انضم إلى المجموعة لتقرأ رسائلها وتشارك.",
    "gr.rules": "القواعد", "gr.you": "أنت",
    "com.confirm_group_aud": "أؤكد أن هذه المجموعة تناسبني ({aud})",
    "err.please confirm the audience of this group": "يرجى تأكيد أن المجموعة تناسبك.",
    "err.meetup already started": "بدأ اللقاء، ولم يعد الحجز متاحاً.",
    "err.the meetup must start in the future": "اختر موعداً لم يأتِ بعد.",
    },
  en: {
    "com.title": "Community", "com.lead": "Keep learning with others in groups led by da'is, and attend meetups at public venues. No private messages between members, and nicknames only.",
    "com.groups": "Groups", "com.meetups": "Muslim community events", "com.all_langs": "All languages",
    "com.members": "{n} members", "com.led_by": "Led by {name}", "com.join": "Join", "com.open": "Open group",
    "com.women": "Women", "com.men": "Men", "com.families": "Families", "com.everyone": "Everyone",
    "com.join_title": "Join “{title}”", "com.nickname": "A nickname other members will see", "com.nick_hint": "Don't use your real name or anything that identifies you.",
    "com.rules": "Group rules",
    "com.rule1": "Be respectful and kind; every question is welcome.",
    "com.rule2": "No private messages, links, phone numbers or account handles.",
    "com.rule3": "The assistant (@sabeeli) answers from approved sources; the da'i reviews and clarifies.",
    "com.rule4": "Abuse is blocked, and repeated abuse stops participation.",
    "com.accept": "I've read the rules and agree", "com.joined": "You joined the group",
    "com.empty_groups": "No groups in this language yet.", "com.empty_meetups": "No upcoming events.",
    "com.spots": "{n} spots left", "com.full": "Full", "com.host": "Hosted by {name}",
    "com.rsvp": "Reserve a spot", "com.rsvp_title": "Register for “{title}”", "com.rsvp_note": "We don't ask for your name or number. You'll get a booking code to show when you arrive.",
    "com.confirm_aud": "I confirm this meetup is for me ({aud})", "com.booked": "Your spot is reserved", "com.code": "Booking code",
    "com.add_cal": "Add to calendar", "com.cancel_rsvp": "Cancel reservation", "com.public_place": "Public venue",
    "com.minutes": "{n} min",
    "com.reg.required": "Booking needed", "com.reg.open": "Walk-in", "com.reg.all": "All events",
    "com.walk_in": "No registration needed: just come", "com.reg_needed": "Registration required", "com.country": "Country", "com.city": "Region", "com.all_countries": "All countries", "com.all_cities": "All regions", "com.age": "Age group",
    "com.age.all": "All ages", "com.age.kids": "Children with a guardian", "com.age.youth": "Youth 18–29",
    "com.age.adults": "Adults 30–59", "com.age.seniors": "Seniors 60+",
    "com.open_to": "Open to", "com.for.all": "All", "com.for.women": "Women", "com.for.men": "Men",
    "com.mine": "My activities", "com.format": "Format", "com.fmt.all": "All", "com.fmt.in_person": "In person", "com.fmt.online": "Online",
    "com.online_place": "Online: the link appears once you book", "com.online_booked": "Online: use \"Meeting link\" at the start time", "com.online_everywhere": "Online meetups show for every country.",
    "com.city_time": "{city} time", "com.happening_now": "Happening now", "com.ended": "Ended", "com.cancelled_by_host": "Cancelled by the host",
    "com.spots_few": "Only {n} spots left", "com.youre_in": "You're in", "com.join_now": "Join now", "com.open_link": "Meeting link",
    "com.cancel_q": "Cancel your booking?", "com.cancel_yes": "Yes, cancel", "com.cancel_keep": "Keep it",
    "com.rsvp_note_online": "We don't ask for your name or number. The meeting link appears once you book, and stays under My activities.",
    "com.rsvp_note_open": "No booking needed: just come. Joining adds it to My activities and tells the host how many to expect.",
    "com.confirm_booking": "Confirm booking", "com.confirm_join": "Confirm", "com.joined_title": "You're on the list",
    "com.next_code": "Show this code at the entrance. It's also under My activities.",
    "com.next_open": "No code needed: just come on time. The details are under My activities.",
    "com.next_online": "Open the link at the start time. It's also under My activities, where a Join button appears 15 minutes before.",
    "com.see_mine": "Go to My activities", "com.mine_device": "Your bookings are saved in this browser.", "com.mine_signin": "Sign in to see them on any device.",
    "com.mine_upcoming": "Coming up", "com.mine_none": "You haven't booked any meetups yet.", "com.browse_events": "Browse events",
    "com.mine_groups": "Your groups", "com.mine_no_groups": "You haven't joined a group yet.", "com.browse_groups": "Browse groups",
    "com.mine_past": "Past and cancelled ({n})",
    "com.online_url": "Meeting link", "com.online_url_hint": "A Zoom, Google Meet or Teams link starting with https://. Only people who book see it.",
    "com.tz_note": "In your device's time zone ({tz}).",
    "err.an online meetup needs an https meeting link": "Add a meeting link starting with https://",
    "err.a meetup in person needs a city and a venue": "Add the city and the venue.",
    "com.series.qawl_amal": "Word and Deed in Islam", "com.series_lead.qawl_amal": "A series linking what we learn with what we do: a short lesson, then putting it into practice together.", "com.series.ramadan": "Ramadan events", "com.series_lead.ramadan": "Shared iftars and open evenings in Ramadan, open to everyone.", "com.register": "Register", "com.join_event": "Join", "com.joined_event": "Joined", "com.leave_event": "Leave", "com.joined_toast": "You joined the event.", "com.join_title_event": "Join “{title}”", "com.going": "{n} going", "com.guest": "Guest",
    "com.confirm_guardian": "I am the child's guardian and will stay with them throughout",
    "gr.back": "All groups", "gr.leave": "Leave group", "gr.ph": "Write a message… tag @sabeeli to ask the assistant",
    "gr.ask_bot": "Ask @sabeeli", "gr.leader": "Group leader", "gr.bot": "AI assistant",
    "gr.deleted": "This message was removed.", "gr.bot_thinking": "Sabeeli is searching the sources…", "gr.needs_leader": "Waiting for the da'i to clarify",
    "gr.muted": "Your participation in this group is paused.", "gr.err.abuse": "Not posted: the message contains abusive language.",
    "gr.err.too_fast": "Slow down a little before the next message.", "gr.err.too_long": "The message is too long.",
    "gr.redacted": "We hid links or contact details from your message to protect privacy.", "gr.not_member": "Join the group to read and take part.",
    "gr.rules": "Rules", "gr.you": "You",
    "com.confirm_group_aud": "I confirm this group is for me ({aud})",
    "err.please confirm the audience of this group": "Please confirm this group is for you.",
    "err.meetup already started": "This meetup has started; booking is closed.",
    "err.the meetup must start in the future": "Choose a time that hasn't passed yet.",
    },
});
