// Community strings. Owner: Mushari.
import { register } from "../../core/i18n.jsx";

register({
  ar: {
    "com.title": "المجتمع", "com.lead": "تابع تعلّمك مع آخرين في مجموعات يقودها دعاة، واحضر لقاءات في أماكن عامة. بلا رسائل خاصة بين الأعضاء، وبأسماء مستعارة.",
    "com.groups": "المجموعات", "com.meetups": "فعاليات المجتمع المسلم", "com.all_langs": "كل اللغات",
    "com.members": "{n} عضو", "com.led_by": "يقودها {name}", "com.join": "انضم", "com.open": "ادخل المجموعة",
    "com.women": "للنساء", "com.men": "للرجال", "com.families": "للعائلات", "com.everyone": "للجميع",
    "com.join_title": "الانضمام إلى «{title}»", "com.nickname": "اسم مستعار يظهر للأعضاء", "com.nick_hint": "لا تستخدم اسمك الحقيقي أو أي معلومة تعرّف بك.",
    "com.rules": "قواعد المجموعة",
    "com.rule1": "الاحترام والرفق في الحوار، والسؤال مرحب به دائماً.",
    "com.rule2": "لا رسائل خاصة، ولا روابط، ولا أرقام هواتف أو حسابات.",
    "com.rule3": "المساعد «@سبيلي» يجيب من المصادر المعتمدة، والداعية يراجع ويوضح.",
    "com.rule4": "الإساءة تُحجب، وتكرارها يوقف المشاركة.",
    "com.accept": "قرأت القواعد وأوافق عليها", "com.joined": "انضممت إلى المجموعة",
    "com.empty_groups": "لا توجد مجموعات بهذا الاختيار بعد.", "com.empty_meetups": "لا توجد فعاليات قادمة.",
    "com.spots": "{n} مقعد متبقٍ", "com.full": "اكتمل العدد", "com.host": "يقدمه {name}",
    "com.rsvp": "احجز مقعداً", "com.rsvp_title": "التسجيل في «{title}»", "com.rsvp_note": "لا نطلب اسمك أو رقمك. ستحصل على رمز حجز تُظهره عند الحضور.",
    "com.confirm_aud": "أؤكد أن هذا اللقاء يناسبني ({aud})", "com.booked": "حُجز مقعدك", "com.code": "رمز الحجز",
    "com.add_cal": "أضف إلى التقويم", "com.cancel_rsvp": "إلغاء الحجز", "com.public_place": "مكان عام",
    "com.minutes": "{n} دقيقة",
    "com.reg.required": "بتسجيل", "com.reg.open": "دون تسجيل", "com.reg.all": "كل الفعاليات",
    "com.walk_in": "لا يلزم التسجيل: احضر مباشرة", "com.reg_needed": "يلزم التسجيل", "com.country": "الدولة", "com.city": "المنطقة", "com.all_countries": "كل الدول", "com.all_cities": "كل المناطق", "com.age": "الفئة العمرية",
    "com.age.all": "كل الأعمار", "com.age.kids": "أطفال مع ولي أمرهم", "com.age.youth": "شباب ١٨–٢٩",
    "com.age.adults": "بالغون ٣٠–٥٩", "com.age.seniors": "كبار ٦٠ فأكثر",
    "com.series.qawl_amal": "القول والعمل في الإسلام", "com.series_lead.qawl_amal": "سلسلة تربط ما نتعلمه بما نعمله: درس قصير ثم تطبيق عملي مع الآخرين.", "com.series.ramadan": "فعاليات رمضان", "com.series_lead.ramadan": "إفطارات جماعية وليالٍ تعريفية في رمضان، مفتوحة للجميع.", "com.register": "سجّل", "com.join_event": "انضم", "com.joined_event": "انضممت", "com.leave_event": "إلغاء الانضمام", "com.joined_toast": "انضممت إلى الفعالية.", "com.join_title_event": "الانضمام إلى «{title}»", "com.going": "{n} منضم", "com.guest": "زائر",
    "com.confirm_guardian": "أنا ولي أمر الطفل وسأحضر معه طوال اللقاء",
    "gr.back": "كل المجموعات", "gr.leave": "مغادرة المجموعة", "gr.ph": "اكتب رسالة… واكتب @سبيلي لتسأل المساعد",
    "gr.ask_bot": "اسأل @سبيلي", "gr.leader": "قائد المجموعة", "gr.bot": "مساعد آلي",
    "gr.deleted": "حُذفت هذه الرسالة.", "gr.bot_thinking": "سَبِيلي يبحث في المصادر…", "gr.needs_leader": "بانتظار توضيح الداعية",
    "gr.muted": "أُوقفت مشاركتك في هذه المجموعة.", "gr.err.abuse": "لم تُنشر الرسالة لأنها تحتوي ألفاظاً مسيئة.",
    "gr.err.too_fast": "مهلاً، انتظر ثوانٍ قبل الرسالة التالية.", "gr.err.too_long": "الرسالة طويلة جداً.",
    "gr.redacted": "أخفينا روابط أو معلومات تواصل من رسالتك حفاظاً على الخصوصية.", "gr.not_member": "انضم إلى المجموعة لتقرأ رسائلها وتشارك.",
    "gr.rules": "القواعد", "gr.you": "أنت",
    "com.confirm_group_aud": "أؤكد أن هذه المجموعة تناسبني ({aud})",
    "err.please confirm the audience of this group": "يرجى تأكيد أن المجموعة تناسبك.",
    "err.meetup already started": "بدأ اللقاء، ولم يعد الحجز متاحاً.",
    "err.the meetup must start in the future": "اختر موعداً لم يأتِ بعد.",
    },
  en: {
    "com.title": "Community", "com.lead": "Keep learning with others in groups led by da'is, and attend meetups at public venues. No private messages between members, and nicknames only.",
    "com.groups": "Groups", "com.meetups": "Muslim community events", "com.all_langs": "All languages",
    "com.members": "{n} members", "com.led_by": "Led by {name}", "com.join": "Join", "com.open": "Open group",
    "com.women": "Women", "com.men": "Men", "com.families": "Families", "com.everyone": "Everyone",
    "com.join_title": "Join “{title}”", "com.nickname": "A nickname other members will see", "com.nick_hint": "Don't use your real name or anything that identifies you.",
    "com.rules": "Group rules",
    "com.rule1": "Be respectful and kind; every question is welcome.",
    "com.rule2": "No private messages, links, phone numbers or account handles.",
    "com.rule3": "The assistant (@sabeeli) answers from approved sources; the da'i reviews and clarifies.",
    "com.rule4": "Abuse is blocked, and repeated abuse stops participation.",
    "com.accept": "I've read the rules and agree", "com.joined": "You joined the group",
    "com.empty_groups": "No groups in this language yet.", "com.empty_meetups": "No upcoming events.",
    "com.spots": "{n} spots left", "com.full": "Full", "com.host": "Hosted by {name}",
    "com.rsvp": "Reserve a spot", "com.rsvp_title": "Register for “{title}”", "com.rsvp_note": "We don't ask for your name or number. You'll get a booking code to show when you arrive.",
    "com.confirm_aud": "I confirm this meetup is for me ({aud})", "com.booked": "Your spot is reserved", "com.code": "Booking code",
    "com.add_cal": "Add to calendar", "com.cancel_rsvp": "Cancel reservation", "com.public_place": "Public venue",
    "com.minutes": "{n} min",
    "com.reg.required": "Booking needed", "com.reg.open": "Walk-in", "com.reg.all": "All events",
    "com.walk_in": "No registration needed: just come", "com.reg_needed": "Registration required", "com.country": "Country", "com.city": "Region", "com.all_countries": "All countries", "com.all_cities": "All regions", "com.age": "Age group",
    "com.age.all": "All ages", "com.age.kids": "Children with a guardian", "com.age.youth": "Youth 18–29",
    "com.age.adults": "Adults 30–59", "com.age.seniors": "Seniors 60+",
    "com.series.qawl_amal": "Word and Deed in Islam", "com.series_lead.qawl_amal": "A series linking what we learn with what we do: a short lesson, then putting it into practice together.", "com.series.ramadan": "Ramadan events", "com.series_lead.ramadan": "Shared iftars and open evenings in Ramadan, open to everyone.", "com.register": "Register", "com.join_event": "Join", "com.joined_event": "Joined", "com.leave_event": "Leave", "com.joined_toast": "You joined the event.", "com.join_title_event": "Join “{title}”", "com.going": "{n} going", "com.guest": "Guest",
    "com.confirm_guardian": "I am the child's guardian and will stay with them throughout",
    "gr.back": "All groups", "gr.leave": "Leave group", "gr.ph": "Write a message… tag @sabeeli to ask the assistant",
    "gr.ask_bot": "Ask @sabeeli", "gr.leader": "Group leader", "gr.bot": "AI assistant",
    "gr.deleted": "This message was removed.", "gr.bot_thinking": "Sabeeli is searching the sources…", "gr.needs_leader": "Waiting for the da'i to clarify",
    "gr.muted": "Your participation in this group is paused.", "gr.err.abuse": "Not posted: the message contains abusive language.",
    "gr.err.too_fast": "Slow down a little before the next message.", "gr.err.too_long": "The message is too long.",
    "gr.redacted": "We hid links or contact details from your message to protect privacy.", "gr.not_member": "Join the group to read and take part.",
    "gr.rules": "Rules", "gr.you": "You",
    "com.confirm_group_aud": "I confirm this group is for me ({aud})",
    "err.please confirm the audience of this group": "Please confirm this group is for you.",
    "err.meetup already started": "This meetup has started; booking is closed.",
    "err.the meetup must start in the future": "Choose a time that hasn't passed yet.",
    },
});
